### ISSUE TITLE
0.4.0e4d0927 consistently losing connection (Galaxy S4)

### ISSUE THREAD

**Issue by glenngrimes** [pazaan/600SeriesAndroidUploader#102]
#### Your Environment

* Uploader Version Number:  0.4.0e4d0927
* Your Android Phone Model Name (e.g. Samsung J1 Ace):  Samsung Galaxy S4
* Android Version Number (e.g. use 4.4 for 4.4.4): 5.0.1
* Network Connection at the time the issue occurred (Wi-Fi, Mobile):  Wi-Fi (only ever used at home over Wi-Fi)
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):  Not sure, was installed in June 2016 and not updated since

#### Brief Explanation of Issue

On Sunday 29/01/2017 we installed 0.4.0e4d0927 uploader on the above phone.  The S4 is connected to CNL and connects correctly to pump, pulls the data and uploads to Azure.  About once per hour or once per two hours it stops connecting with a 'timeout' message on the screen.  We have to click on 'Read Data Now' to have it connect correctly again and upload which it does for a similar period of time and then fails again.  At all times the S4 + CNL is within 1mtr of our daughter with clear sight to her.
We only use it at night so this is obviously tough on sleep patterns for the parents.  
On Wednesday 01/02/2017 we have reverted back to 0.4.0 and it is working fine for last 2 nights (well, the odd blip but nothing like the previous 3 nights).

#### Uploader Error Code

Sorry, I have installed the older version of the software to I don't have the errors.  It was a standard consistent message like:
HH:MM:SS Timeout connecting to .....

#### Steps to Reproduce (for bugs)

1.  Use a Samsung Galaxy S4 with above android on it.  Install 0.4.0e4d0927 Android Uploader on it
2.  Connect to pump and allow to start uploading
3.  Wait for communications to stop.  
4.

#### Severity Score

3 -- impact on the parents who are looking after their child as we are required to get up once per hour or two to reset it.

**Comment by volkerrichert** [comment]
are you able to compile it yourself? Pogman has done a great improvement. Pazaan, pogman and myself are running it for a while.

**Comment by volkerrichert** [comment]
P.S: I'm using the same device. Running CM on it.

**Comment by glenngrimes** [comment]
Sorry guys, I never saw the updates you added back in March.  I logged in to see if I could see any issue relating to the S4 5.0.1 polling bug with Beat the Mountain when I saw I had this open.  It might be redundant now with the release of BtM so up to you guys whether you want to close it out.

**Comment by pazaan** [comment]
Fixed by #143
