### ISSUE TITLE
Validate the time on the uploader device.

### ISSUE THREAD

**Issue by pazaan** [pazaan/600SeriesAndroidUploader#115]
It's possible that the time on the uploader device is incorrect, leading to incorrect timestamps on uploaded data. Use either the NS server time, or another server-authoritative time to validate the time on the uploader.

**Comment by Pogman** [comment]
A check has been added to compare the NS server and local times and if they are out by +/- 10 minutes the user is alerted and a message with a suggestion how to fix.

If times are then changed on the uploader that makes a mess of the data it will automatically reset the db and re-pull the history from the pump and send the fixed times to NS.

Closed - completed and available in 0.7.0 release
