### ISSUE TITLE
Trend arrows are truncated on Galaxy S7 Edge

### ISSUE THREAD

**Issue by pazaan** [pazaan/600SeriesAndroidUploader#123]
![cut off arrows](https://user-images.githubusercontent.com/96943/27897087-bb88efd0-6250-11e7-93de-8c5364ca61b4.jpg)

Trend arrows are being truncated in Uploader version 0.5.0 on a Galaxy S7 Edge.

**Comment by pazaan** [comment]
On Android 7.0

**Comment by volkerrichert** [comment]
can it be reproduced by genymotion? my test version is expired

**Comment by Pogman** [comment]
I was able to produce a similar effect in genymotion when elements would get cut off and have made a fix to the layout code and available in next release.

If any user that has had this issue could report if it still happens or not in (v5.1) that would be great.
