### ISSUE TITLE
Make trend arrows consistent across different OS versions

### ISSUE THREAD

**Issue by pazaan** [pazaan/600SeriesAndroidUploader#140]
We're currently using Unicode for rendering the trend arrows, but this renders differently on different OS versions, especially the 45 degree arrows.

Either rotate straight arrows using https://stackoverflow.com/questions/38202753/display-the-text-as-diagonally-at-45-in-textview, or use http://zavoloklom.github.io/material-design-iconic-font/icons.html, since we have com.mikepenz:ionicons-typeface as a dependency now.

**Comment by Pogman** [comment]
Yes - I hadn't realised that the 45 degree angles were part of that font set when I looked. I'll get these added for 5.1 too.

Thinking of increasing the log size to go with these ui fixes. It covers mostly around 8 hours now but maybe that should be 12 to 24?

**Comment by pazaan** [comment]
Depends. If it's disk-backed, then that would be fine. If it's going to eat up a lot more memory, then it might not be the best.

**Comment by Pogman** [comment]
At the moment it's just memory but I think long term the log should be persisted between restarts and disk based. So future work then.

**Comment by Pogman** [comment]
Looks like the mikepenz dependency doesn't have the arrows we need.

**Comment by Pogman** [comment]
Arrg looking at the wrong thing - found the dependency needed for those
Some days.....

**Comment by Pogman** [comment]
No right-down 45 degree arrow bah - got all of them except that

**Comment by Pogman** [comment]
Anyways I used this for the missing arrows: textViewTrend.setRotation(45);

But it don't feel quite right ;)

**Comment by pazaan** [comment]
What about the "cmd" icon set? https://materialdesignicons.com/cheatsheet. It should be cmd-arrow-bottom-right.

**Comment by Pogman** [comment]
Dosn't seem to be in the mikepenz stuff thoughwhich is a nice easy way of doing things.

**Comment by pazaan** [comment]
It is in the mikepenz stuff, you just need to add `compile 'com.mikepenz:community-material-typeface:1.9.32.2@aar'`

**Comment by Pogman** [comment]
closing - fixed in 0.6+
