### ISSUE TITLE
CGM trend status is incorrect when one of the CGM errors is present

### ISSUE THREAD

**Issue by pazaan** [pazaan/600SeriesAndroidUploader#141]
This is most likely to do with not having determined how to accurately parse the CGM status byte.
We're using this for the trend, but it looks like it also contains other status information.

For example, when I have a CGM battery low warning on the pump, the trend arrows do not show at all:
<img width="644" alt="no trend arrows" src="https://user-images.githubusercontent.com/96943/28352010-581869c2-6c86-11e7-931f-c30b5d8bc1ee.png">

**Comment by Pogman** [comment]
Does the trend arrow show on the pump screen when transmitter battery is low?

A record of the medtronic status messages from scenarios like this would be useful.

**Comment by Pogman** [comment]
Ah finally able to see the cause of this as I have a transmitter battery at 0%.

The lower nibble of the trend byte can contain a value where we expect it to be 0. The upper part contains the trend. Solution was to just mask it with 0xF0 before parsing the trend arrow.
