### ISSUE TITLE
Extract alarm flags from pump status message

### ISSUE THREAD

**Issue by cfaagaard** [pazaan/600SeriesAndroidUploader#142]
hi guys,

thank you for your great work. 
I think I found out some more "byte-meaning" in the status message.
In the index 72 you have a 2 byte (int16) there is a warning number (ex. 810) and in index 74 and 78 the date for the warning is shown. By downloading the carelink-csv I have found the following warnings:

    public enum Warnings: Int16
    {
        No_Warning_0=0,
        Alert_On_High_816 = 816,
        Alert_Before_High_817 = 817,
        Alert_On_Low_while_suspended_803 = 803,
        Battery_Depleted_11 = 11,
        Device_Alarm_100 = 100,
        Device_Alarm_109 = 109,
        Device_Alarm_73 = 73,
        Device_Alarm_84 = 84,
        No_Delivery_7 = 7,
        Low_Battery_104 = 104,
        Low_Reservoir_105 = 105,
        Sensor_Alert_Calibrate_Now_775 = 775,
        Sensor_Alert_Calibration_Error_776 = 776,
        Sensor_Alert_Calibration_Reminder_869 = 869,
        Sensor_Alert_Low_Transmitter_870 = 870,
        Sensor_Alert_Sensor_Error_801 = 801,
        Sensor_Alert_Change_Sensor_778 = 778,
        Sensor_Alert_Lost_Sensor_780 = 780,
        Sensor_Alert_Lost_Sensor_781 = 781,
        Sensor_Alarm_786 = 786,
        Sensor_Alarm_787 = 787,
        Sensor_Alarm_788 = 788,
        Sensor_Alarm_795 = 795,
        Sensor_Alarm_798 = 798,
        Sensor_Alarm_799 = 799,
        Suspend_Before_Low_Alarm_quiet_810 = 810,
        Suspend_Before_Low_Alarm_811 = 811,
        Basal_Delivery_Resumed_Alert_quiet_806 = 806,
        Suspend_Before_Low_Alarm_patient_unresponsive_medical_device_emergency_812 = 812,
        Basal_Delivery_Resumed_Alert_maximum_suspend_reached_808 = 808,
        Basal_Delivery_Resumed_Alert_glucose_still_low_maximum_suspend_reached_814 = 814,

    }

**Comment by pazaan** [comment]
Thanks @cfaagaard, this is super-handy! Can you please clarify what you mean by index 72 and index 74?

**Comment by pazaan** [comment]
@cfaagaard I hope you don't mind, but I added some extras I found in my own CSVs 😄

**Comment by cfaagaard** [comment]
Index number in the byte stream.
(On mobil right now.. clarify later. Ok?)

**Comment by cfaagaard** [comment]
Index 74 and 78 is the rtc and offset.

**Comment by pazaan** [comment]
A clarification later would be good. 😄
I don't think we're starting from the same index.

**Comment by cfaagaard** [comment]
I am on the decrypted payload. To "calibrate" our index: I have: 
        [BinaryElement(69)]
        public byte BolusWizardRecent { get; set; }
        [BinaryElement(70)]
        public Int16 BolusWizardBGLRaw { get; set; }

**Comment by cfaagaard** [comment]
[BinaryElement(70)] 
public Int16 BolusWizardBGLRaw { get; set; }

start at index 70 and it is a "Int16" two byte.j So the warning and datewarning should be right after your BGL.
I have been playing around with a binary serialization of the messages. Rightt now I am testing the framework on a c#/uwp client on a raspberry pi 3.

**Comment by cfaagaard** [comment]
And the whole class have an attribute: [BinaryType(IsLittleEndian = false)]
which tells the serialization that it is a bigEndian array.

**Comment by pazaan** [comment]
Got it, thanks! I have BolusWizardBGLRaw as 0x49 (73), so that's where we weren't aligned. Thanks again! I'll make sure to code this up 😄

**Comment by cfaagaard** [comment]
And thank you for all your Work.

**Comment by pazaan** [comment]
It's my pleasure! Is your project on GitHub? I'm currently working on a Node app for Pi/CHIP/Whatever.

**Comment by cfaagaard** [comment]
Not on github, yet. Have No experince in using github as source control. Using Microsoft tfs right now. But plan to move to github.

**Comment by cfaagaard** [comment]
The c# is coded in .net standard 1.4 so it should run on Linux/Windows platform. I wanted to try out the Windows 10 IOT in the pie.

**Comment by cfaagaard** [comment]
Looked into the github source control from visual studio. It was not that hard, so I have published latest version of my project. https://github.com/cfaagaard/CGM.NET

**Comment by cfaagaard** [comment]
Are there any central nightscout ressource where you can notify the community of the project I have just published? 
Not so much "normal" users, but more developers.

**Comment by Pogman** [comment]
Thanks @cfaagaard some good stuff there.

**Comment by cfaagaard** [comment]
Thanks @Pogman and thank you for your work on the 600uploader. As I am saying in the readme.md; I am standing on the shoulders of giants.

**Comment by Pogman** [comment]
offset in the uploader:
warning = statusBuffer.getShort(0x4B)

The downside with this warning is that it is only available while the alert shows on the pump screen. If a user cancels the alert between uploader polls we will never see it.

**Comment by Pogman** [comment]
Pulled these from a year of saved Carelink data:

Alert Before High (817)
Alert Before Low (805)
Alert On High (816)
Alert On Low (802)
Alert On Low while suspended (803)
Basal Delivery Resumed Alert, maximum suspend reached (808)
Basal Delivery Resumed Alert, quiet (806)
Basal Delivery Resumed Alert, settings change (815)
Battery Depleted (11)
Battery Out Limit Exceeded (6)
Device Alarm (100)
Device Alarm (110)
Device Alarm (113)
Device Alarm (73)
Device Alarm (84)
Low Battery (104)
Low Reservoir (105)
No Delivery (7)
No Reservoir (66)
Sensor Alarm (787)
Sensor Alarm (788)
Sensor Alarm (789)
Sensor Alarm (790)
Sensor Alarm (791)
Sensor Alarm (795)
Sensor Alarm (797)
Sensor Alarm (798)
Sensor Alarm (799)
Sensor Alert: Calibrate Now (775)
Sensor Alert: Calibration Reminder (869)
Sensor Alert: Lost Sensor (780)
Sensor Alert: Lost Sensor (781)
Sensor Alert: Rising Rate of Change (784)
Sensor Alert: Sensor End (794)
Sensor Alert: Sensor Error (801)
Sensor Alert: Weak Signal (796)
Suspend Before Low Alarm, patient unresponsive, medical device emergency (812)
Suspend Before Low Alarm, quiet (810)
Suspend On Low Alarm (809)
Sensor Alarm (786)
Sensor Alert: Calibration Error (776)
No Delivery After Estimate (8)
Sensor Alert: Change Sensor (777)
Device Alarm (111)
Sensor Alert: Low Transmitter (870)
Device Alarm (58)
Device Alarm (70)

**Comment by cfaagaard** [comment]
this is great. And yes your a correct @Pogman; it is more an "ActiveAlert" than just an "Alert". But it is great for a parent (like me :-)) when my kid gets a little warning/alarm/alert tired. Or at night when he does not hear the alarm.

**Comment by cfaagaard** [comment]
now I just need to find out how to utilize this ActiveAlert in the nightscout website. Any suggestions? Are there any Alert functionality?

**Comment by cfaagaard** [comment]
Beside nightscout website, I use Microsoft flow and wunderlist for our "diabetes management", so I am thinking maybe just a notification/alert via wunderlist just might do the trick...

**Comment by Pogman** [comment]
The alert could be sent to NS as a "Note" or "Announcement" or "D.A.D. Alert" and use the built-in IFTTT to do something with that.

http://www.nightscout.info/wiki/labs/ifttt-integration

**Comment by cfaagaard** [comment]
When the Sgv-value  in the statusresponse is over 400 it looks like the sgv-value is a Alert number instead. And sometimes the actual Alert-bytes are also filled out. So there are two alert "placement".
I have observed the following values instead of sgv:
        Warmup_769 = 769,
        Need_Calibration_770 = 770,
        Sensor_Alert_Change_774 = 774

**Comment by pazaan** [comment]
Here are the meanings of those numbers for you:

769: SENSOR_INIT;
770: SENSOR_CAL_NEEDED;
771: SENSOR_ERROR;
772: SENSOR_CAL_ERROR;
773: SENSOR_CHANGE_SENSOR_ERROR;
774: SENSOR_END_OF_LIFE;
775: SENSOR_NOT_READY;
776: SENSOR_READING_HIGH;
777: SENSOR_READING_LOW;
778: SENSOR_CAL_PENDING;
779: SENSOR_CHANGE_CAL_ERROR;
780: SENSOR_TIME_UNKNOWN;

**Comment by cfaagaard** [comment]
aahhh, thanks.

**Comment by cfaagaard** [comment]
Observed this today:
        
Device_Alarm_Change_Battery_73 = 73,
Device_Alarm_Insert_Battery_84 = 84,

**Comment by Pogman** [comment]
Closing this out now... if I see another alarm code I'll scream ;) v0.7.0 now handles all things alerts and alarms.
