### ISSUE TITLE
Charging with QI 

### ISSUE THREAD

**Issue by SJoWie80** [pazaan/600SeriesAndroidUploader#148]
#### Your Environment
* Uploader Version Number: v0.5.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung Galaxy S6
* Android Version Number (e.g. use 4.4 for 4.4.4): 7.0
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wifi

#### Brief Explanation of Issue
If the phone is full while  charging true QI the CNL gets (software) disconnected from OTG.
I need to reconnect it manualy to resume operation.

Regards,
Joey

**Comment by volkerrichert** [comment]
my S4 (with QI antenna) is at 96%... I'll take a look.

**Comment by Pogman** [comment]
This may be a power issue when the phone hits 100% charge. It may briefly have no power on the port and if this happens in mid comms with the CNL it can crash it requiring a disconnect/reconnect.
