### ISSUE TITLE
[Feature] Widget for Lockscreen

### ISSUE THREAD

**Issue by SORC3r3r** [pazaan/600SeriesAndroidUploader#157]
A Widget which can be displayed on the lock-screen would be a nice feature.
Is this planned?
Maybe enabling of warning signals if the data reaches some configurable values would be nice as well.

Great work!
Regards

**Comment by Pogman** [comment]
There is some stuff in the works that will particularly suit primary users rather then remote followers. As a taster here's a early WIP screenshot:

![ns-uploader-n1](https://user-images.githubusercontent.com/7413594/30614461-640d7852-9d83-11e7-80ba-2c52423a5e00.png)

**Comment by volkerrichert** [comment]
hey @Pogman!

if teh uploader is mainly running as a service this would be really cool!

BTW: i find it more comfortable to have a time for next calibration instead of a delta or both

**Comment by volkerrichert** [comment]
this is a notification, right? Will/Can it be displayed partially on the locked screen?

**Comment by volkerrichert** [comment]
oh,no.... volker, look at the titel!!!

**Comment by Pogman** [comment]
It's a notification rather then a widget so it does go on the lockscreen / pulldown where it's most useful but there's no reason not to have a widget for the launcher screens too.

User option for calibration by time / hours remaining noted. 

BTW if you get a chance try out the develop-treatments branch as this extra pump info is pushed to NS and might be more use for you as follower.

**Comment by SORC3r3r** [comment]
I was thinking about the value to be displayed directly on the lock screen, so you do not have to pull down or unlock the phone.
I will give it a try and keep you updated :)

**Comment by iliaskap** [comment]
Hi ! When will be this kind of notifications available ? It's nice to see them on a smartwatch ...

**Comment by cypherghost** [comment]
How do I download the software on to my new Note 8? Just replaced my old phone...

Please send me the link, to cyclopsmedia@comcast.net. TIA!

**Comment by pazaan** [comment]
@cypherghost - you can find the current download link on the ["Releases" page](https://github.com/pazaan/600SeriesAndroidUploader/releases). I won't link to the exact one, because that won't be helpful to anyone browsing here in future.

**Comment by Pogman** [comment]
closing - feature available on 0.6+
