### ISSUE TITLE
uploader working fine.  loading to nightscout page very sporadic and will not function for hours at a time

### ISSUE THREAD

**Issue by nightscout11** [pazaan/600SeriesAndroidUploader#158]
#### Your Environment

* Uploader Version Number:
* Your Android Phone Model Name (e.g. Samsung J1 Ace):
* Android Version Number (e.g. use 4.4 for 4.4.4):
* Network Connection at the time the issue occurred (Wi-Fi, Mobile):
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by Pogman** [comment]
closing - nightscout / mlab issue
