### ISSUE TITLE
Showing closed-loop-67-G micro-boluses on nightscout

### ISSUE THREAD

**Issue by kretch** [pazaan/600SeriesAndroidUploader#167]
I would like to see the micro boluses the 670G does ( in closed-loop mode)  on nightscout.

#### Your Environment
Latest version of uploader
S8+, OTG to CNL24, uploading to NS site http://yaronbginfo.herokuapp.com/
Just FYI A Dexcom G5 also uploads to the same site

#### Brief Explanation of Issue
NA

#### Uploader Error Code
NA

#### Steps to Reproduce (for bugs)
NA

#### Severity Score
1

**Comment by pazaan** [comment]
That work is already in progress.

**Comment by kretch** [comment]
Thanks. Is that part of the develop-indra branch?

**Comment by pazaan** [comment]
No, it's in a local branch on my machine at the moment. I'll push it to a separate branch so that we don't interrupt getting an Indra release out ASAP.

**Comment by kretch** [comment]
Great, thanks! I was able to build Indra and use it on my s8, so looking
forward to trying out the local branch

**Comment by kretch** [comment]
Hi Lenhart
Would it be possible to get access to the branch with the micro-bolus upload changes?
TIA

Yaron

**Comment by pazaan** [comment]
It's being worked on at https://github.com/pazaan/600SeriesAndroidUploader/tree/pazaan/develop-indra-670G

**Comment by kretch** [comment]
Thanks much!

**Comment by Pogman** [comment]
@kretch there are some issues with the 670G that are being worked on but we are limited when it comes the devs that have a 670G to work with - if your interested in trying out the debug version and your ok with us viewing your NS site please build and run the branch here: https://github.com/pazaan/600SeriesAndroidUploader/tree/develop-indra-670G-debug

**Comment by kretch** [comment]
I built develop-indra-670G , installed on Samsung S7, and you can see the
NS results in http://yaronbginfo.herokuapp.com/

Thanks again!

**Comment by Pogman** [comment]
It needs to be this branch "develop-indra-670G-debug" to be of use for us.

**Comment by kretch** [comment]
Building that now, should have it uploading data into NS within the hour.

**Comment by Pogman** [comment]
cool - thanks!

You can just let it run as we need to see the debug data as you use it over time.

**Comment by kretch** [comment]
Ok,debug version installed and running

**Comment by kretch** [comment]
Just FYI- The CNL keeps disconnecting with the debug version (vs. in the
non-debug indra 670G, where the CNL doesn't disconnect)

**Comment by Pogman** [comment]
ok shouldn't be doing that at all - what error is it showing in the log on your uploader? also you can go into the uploader settings under debug and turn on "extended errors"

try restarting your phone and if it still does it try clearing the app data

**Comment by kretch** [comment]
ok, changed phones and uploader running again.

**Comment by Pogman** [comment]
great - I see some debug data coming through too - thanks for the help

**Comment by kretch** [comment]
App keeps crashing (Nougat SDK 24, I'm trying to rebuild the APK on 24 just
to be sure)

**Comment by aboncher** [comment]
Yeah, keeps crashing at the end of attempting to get history. Actually, I see the full SG history on the uploader graph, but it never makes it to nightscout.

[info.nightscout.android_issue_1_crash_5A5E7A1802BE00017C5554A0765DEB63_7c47ed64fb0b11e7b2a556847afe9799_0_v2.txt](https://github.com/pazaan/600SeriesAndroidUploader/files/1637038/info.nightscout.android_issue_1_crash_5A5E7A1802BE00017C5554A0765DEB63_7c47ed64fb0b11e7b2a556847afe9799_0_v2.txt)

**Comment by Pogman** [comment]
ok I'll have a look

**Comment by Pogman** [comment]
Updated debug branch - should be working ok now

**Comment by aboncher** [comment]
Running it now, looks to be working well! 

Other note: I see lots of Fingerstick BG entries (that I didn't take). They show the same BG value that I used for my most recent calibration..

**Comment by kretch** [comment]
Seems to be running well for me as well. Thanks!

**Comment by kretch** [comment]
App is crashing again now, only returns to working after "clear data"

**Comment by Pogman** [comment]
the pump records a lot of bg data on the 670 and the debug ver will show me this in detail for now
what is the crash error?
would it be ok to see your NS site? it would be really useful for this - you can message me on Gitter

**Comment by kretch** [comment]
Sure, http://yaronbginfo.herokuapp.com/
The crash error is just the generic "600 Series Uploader has stopped".

**Comment by Pogman** [comment]
@kretch  sorry thought it was @aboncher :) I was talking too - it's late here

**Comment by kretch** [comment]
np :) If you need the site info, let me know.

**Comment by kretch** [comment]
BTW, the fabric crash URL is
https://fabric.io/myself11111111111516153267/android/apps/info.nightscout.android/issues/5a5eae258cb3c2fa63faffcb?time=last-seven-days

**Comment by aboncher** [comment]
@Pogman  https://abns.herokuapp.com

**Comment by Pogman** [comment]
@aboncher thanks for that

**Comment by Pogman** [comment]
@aboncher those extra bgs you see are not part of this versions code - strange. The code that generates that type of BG entry (top and bottom of graph) doesn't even exist is this version, it does in the v5.1 release version.

**Comment by aboncher** [comment]
I also ran the release version today. So if that's a known bug in the release it makes sense.

**Comment by Pogman** [comment]
ok must be to do with that - do you use the meal wizard and enter carbs etc or just bolus a unit amount for food? this is an area I'm looking to target over the next few days with the feedback from this version.

**Comment by aboncher** [comment]
In automode with 670g you have to use the bolus wizard. You can only adjust BG and carbs input, not the total units.

**Comment by Pogman** [comment]
You always have to enter carbs?

**Comment by aboncher** [comment]
You can only adjust the 2 inputs, BG and carbs. You can leave carbs at 0 and it will calculate a correction if needed.

**Comment by Pogman** [comment]
Great thanks

**Comment by Pogman** [comment]
new version uploaded

**Comment by kretch** [comment]
Thanks much! Still in the indra-670G-debug branch?

**Comment by aboncher** [comment]
Running it now :)

**Comment by kretch** [comment]
It's been uploading steadily for the last 30min- looking good!

**Comment by Pogman** [comment]
@aboncher data coming through from new update 

@kretch yours still looks like it's on an older version

**Comment by kretch** [comment]
@pogman- thanks, I changed to the latest code and restarted. Is the version
correct now?

**Comment by Pogman** [comment]
looks like it's still the old one - it the note it drops to NS every 30mins you should see a value like "AI: 3.45" and it's missing.

**Comment by aboncher** [comment]
@kretch make sure you're pulling correctly, I had 1 merge conflict I had to resolve.

**Comment by kretch** [comment]
Sorry about that- apparently I'm building it incorrectly somehow.

**Comment by Pogman** [comment]
Another update today - some nice stuff in this one!

**Comment by aboncher** [comment]
Pulling carbs from bolus events now 👍 👍

**Comment by Pogman** [comment]
Cool - run a profile update too as it adds a closed loop type in there

**Comment by aboncher** [comment]
Ran a profile update, but I'm not sure what I'm looking for

**Comment by aboncher** [comment]
Ohhhhhhhh the temp basal displayed is from micro bolus rate

**Comment by Pogman** [comment]
it should show when auto mode kicks in and out - you may need to leave it run a while

**Comment by aboncher** [comment]
Ah cool. I don't expect to transition in and out of auto mode very often.

**Comment by aboncher** [comment]
The Basal Estimate/ Temp Basal display seems to have stopped working. It's displaying my manual mode basal rate again.

**Comment by Pogman** [comment]
you would actually be receiving a 0.0 rate and that's what the "Closed Loop" profile type is for but it needs to be triggered to kick in. When you get a microbolus it will work out the equivlent temp rate over 5 mins and show that - it may start showing the transition and the zero rates when there is more history pulled

**Comment by Pogman** [comment]
you can get a better idea of that by manually adding a "Profile Switch" set to 24 hours ago as the "Closed Loop" type - enter that via the treatments button in NS

**Comment by Pogman** [comment]
and there may be dragons (bugs!) with profile use in NS and it shownd be showing a zero rate there but it doen't always so I'm looking at a workaround for that

**Comment by Pogman** [comment]
the actual graph is right though

**Comment by aboncher** [comment]
I did the profile switch (I think) but still see the the manual mode basal rate displayed. I'll give it some time, but it's weird that it worked for exactly 1 packet...

![image](https://user-images.githubusercontent.com/7940119/35132892-50847e80-fc82-11e7-86fd-08c811319f33.png)

**Comment by Pogman** [comment]
I don't think NS likes the use of 0.0 rates in the profiles bah - Also you will only get updates to the auto mode basal when it pulls other history items like bolus which trigger realtime. This might get an option to schedule on a timer but it will such pump battery life.

**Comment by aboncher** [comment]
In that case I think you'd want some sort of filtering on the micro bolus -> basal rate conversion. 

Do you guys have a gitter room setup for this project?

**Comment by Pogman** [comment]
Sure - you can message me on gitter or https://gitter.im/pazaan/decoding-contour-next-link is more generalised for stuff related to this

**Comment by Pogman** [comment]
@aboncher workaround for basal not showing - go into the profile editor and change the closed loop basal rate to 0.000001 and NS will treat it as zero and show it

**Comment by aboncher** [comment]
I didn't have Render Basal checked on my NS website.. Forgot about it when I turned it off since it wasn't helpful with 670g, until now! 

It works without the 0.000001 work around.

**Comment by kretch** [comment]
Works for me as well (hope I'm using the correct version this time...)
[image: Inline image 1]

**Comment by aboncher** [comment]
My micro bolus data stopped showing up, everything else seems to be working fine

![image](https://user-images.githubusercontent.com/7940119/35181126-10c37482-fd71-11e7-8b19-6f4a8bc2d935.png)

**Comment by Pogman** [comment]
The microbolus can only be read from the history data and that is only trigger on main events like bolus or bg etc

The RC for this version will be pushed in the next hour and has an option to set update frequency when the pump is in auto mode. Check that out in system settings, it defaults to 60mins it would be great if you could try 15 mins and so on - this will affect pump battery lifetime, to what degree would be interest to hear.

Thanks for testing - With the RC can you clear the app data before install as it would be useful to know there is nothing hanging around from the debug version. Also I'd recommend going into mLab and deleting the entries and treatments db's, you can get your history back via the uploader.

**Comment by Pogman** [comment]
Indra RC1 branch is up.

**Comment by Pogman** [comment]
@aboncher there's some extra data your missing out on that is viewable in NS: these are the recommended settings for NS to use with Indra.
![indra-connection-strings](https://user-images.githubusercontent.com/7413594/35186779-be6a24a0-fe11-11e7-99e6-eae4eab28548.JPG)

**Comment by aboncher** [comment]
Thanks!

Are the recommended NS settings documented anywhere?

**Comment by Pogman** [comment]
Docs are a bit thin on the ground really, we could do with some volunteers digging in with those. Did you see the image attached to my last post? Those are all you need.

**Comment by aboncher** [comment]
Yep, I got it working now, thanks. Was getting at the idea a new user wouldn't know which settings to use to get the most out of these features.

**Comment by useraps** [comment]
Hello, is it possible to see just text in nightscout, if the 670G is in either AutoMode or Manual Mode? I'm a T1 dad of a 6 yr old and sometimes I have to fight with him just to get to his pump 8~). Thanks for all the work you guys put in to this.  Thank you very much.

Go Eagles!!

John

**Comment by Pogman** [comment]
@useraps auto mode is shown and you will have the option to schedule how often this updates to NS.
![ns-670g-automode](https://user-images.githubusercontent.com/7413594/35297316-82616452-0076-11e8-8061-db49a68ef366.JPG)

**Comment by Pogman** [comment]
@aboncher I've uploaded some final changes to the RC branch and as a last sanity check could you build and run it. All being well this will go out today or tomorrow.

BTW you should see suggestions for your NS site for getting the best use out of it. A confirmation this is happening and overall that it's running as expected would be great - thanks.

**Comment by aboncher** [comment]
Everything running and I do see the suggestions displayed, pretty nice.

Minor suggestion would be to make suggestions a different color to stand out from the more debug-oriented messages. So users know when the app is actually trying to tell them something.

**Comment by kretch** [comment]
Just a quick and somewhat unrelated question- what's the query needed to
remove the DEBUG entries from mlab?

**Comment by Pogman** [comment]
I don't know off hand. I just delete the treatments db in mLab and clear the app data so it pulls the history again and writes it all back to the db.

**Comment by Pogman** [comment]
closing - feature available on 0.6+
