### ISSUE TITLE
What frequency does the Contour Next Link Meter work on and is it possible to use just a phone to communicate with the pump cgm

### ISSUE THREAD

**Issue by Rytiggy** [pazaan/600SeriesAndroidUploader#170]
Im curious if you knew how the pump communicates with the Contour next link meter and if a phone can produce the same connection type as the next link meter?

**Comment by pazaan** [comment]
The pump communicates with the CNL using IEEE 802.15.4 over 2.4GHz. The phone on its own can't do this. We also don't yet know the Over the Air encryption mechanism used. Once we figure that out, we could make something like a RileyLink2.4

**Comment by wright-david** [comment]
Hi

Unfortunately I can't locate the post/comment, but I'm pretty sure Jesus posted a few months back that he had broken the OTA encryption

BRs

David


________________________________

**Comment by HenrikHL** [comment]
I am pritty sure I also saw a post a couple of months ago regarding breaking the OTA encryption... Also cannot find it - have just been looking...
