### ISSUE TITLE
Backfill not working after pump change

### ISSUE THREAD

**Issue by whooze** [pazaan/600SeriesAndroidUploader#173]
#### Your Environment

* Uploader Version Number: 0.5.1-44-g33584b9
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung S7
* Android Version Number (e.g. use 4.4 for 4.4.4): 7.0
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): WiFi

#### Brief Explanation of Issue

Got a replacement pump from Medtronic. Treatments, backfills and basal rates are not working. Installed the first Indra version I used, but didn't work. Compiled a new apk with latest source and didn't work either. App crashes when I activate Crashalytics so no good logging availible :/

#### Uploader Error Code
PUMP history: requested
  12/01/2018 23:58:47 - 13/01/2018 09:13:46
Communication Error: 
Pump Sent a NAK(304:0A) response

#### Severity Score
4 - once you have gotten used to backfill and treatment info you don't want to be without it

**Comment by Pogman** [comment]
Ok that doesn't sound good and I'm concerned that a firmware change on the pump could be an issue here. Can you have a look on the pump on the status screen and note down the pump version number and the other version numbers too so we have a record.

Also can you clear the app data and start it over just to rule out anything with that.

**Comment by Pogman** [comment]
There is a bug that can crash the uploader when there is no data for a period it's trying to pull but you don't seem to have that problem. Actually when you reset the app data, do not turn on the "sync" option in the nightscout settings so that it will limit the backfill period.

**Comment by Pogman** [comment]
What is it doing exactly when you "Update pump profile"? what error does it report?

**Comment by whooze** [comment]
Yeah, the version numbers sure is different :(
<table>
<tr><td><b></b></td><td><b>Old Pump</b></td><td><b>New Pump</b></td></tr>
<tr><td>Version</td><td>2.9D</td><td>4.1D</td></tr>
<tr><td>Motor App</td><td>1.9A</td><td>2.6A</td></tr>
<tr><td>Main Intern</td><td>1.0A</td><td>2.4A</td></tr>
<tr><td>Motor Intern</td><td>1.0A</td><td>2.3A</td></tr>
<tr><td>TelD</td><td>1.0A</td><td>1.0A</td></tr>
<tr><td>Compression</td><td>1.0A</td><td>2.1A</td></tr>
</table>

**Comment by Pogman** [comment]
Ok - I really hope it's not a firmware issue and is something related to a near empty pump history. Can you try the other things I suggested and let me know. After that I might get you a debug apk.

**Comment by whooze** [comment]
It reads the profile just fine and sends it to nightscout (at least according to the logs in the app, can verify that on mlab too.
PUMP history is then requested and fails with communication error:
NAK(304:0A)

**Comment by Pogman** [comment]
Ok and what about resetting the app data? and just using the default settings.

**Comment by whooze** [comment]
Yeah, I did reset the data, enteded the ns-stuff and that's when I got this result

Been using the new pump since wednesday evening

**Comment by Pogman** [comment]
With default settings it will attempt to get history for the last 7 days over several polls. Did it finish any of the history pulls or was there always a NAK error?

**Comment by whooze** [comment]
always a NAK error as far as I can see

**Comment by Pogman** [comment]
ok - debug apk time - I'll message you on Gitter when I have a version for you to try. You will need to go into the debug settings and turn on the remote debugging.

**Comment by whooze** [comment]
sure thing.

I'll install it on the two phones I use as uploaders to collect as much data as possible

**Comment by Pogman** [comment]
closing - fixed on 0.6+
