### ISSUE TITLE
Always Communication Noisy/Busy on Indra Uploader w/ 670G

### ISSUE THREAD

**Issue by YYGIRL** [pazaan/600SeriesAndroidUploader#174]
I am currently using the Indra Uploader on my 670G and always get communication noisy/busy, even when the phone / meter is right next to the pump and in a quiet environment.
#### Your Environment

* Uploader Version Number: Happened on two devices
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung Galaxy S6 Edge+, Motorola Droid Mini
* Android Version Number (e.g. use 4.4 for 4.4.4): Samsung is 6.0 and Moto is 4.4
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wi-Fi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):
0.10.2-release-20171201

#### Brief Explanation of Issue

Always getting communication busy / noisy error. I can get basic information for pump (insulin left) but not getting temp basals, carbs entered, bolus information, etc.

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Severity Score
 3

Extra information on bolus / carbs / basals would be extremely helpful on taking care of my 8yo son from a remote location. Thank you!

**Comment by Pogman** [comment]
Are you using the 670G code branch?

Also for the 670 it's likely to have lots of issues and work is ongoing for that pump.

If you go into the debug settings turn on "extended errors" as you might see some extra details related to communications.

**Comment by YYGIRL** [comment]
Damn, I missed the 670G specific code branch. Let me do that. Thanks for the tip on the extended errors too. Y'all are the best.

**Comment by Pogman** [comment]
At the moment when in auto mode on the 670 it's triggering a history request every poll and it's too often and you will probably see the busy error - the pump will drop a request when busy. Also it takes very little radio noise to kill a connection too. There should be around 20 history requests per day with the odd error but at the moment with the 670 it's up near 300!

**Comment by YYGIRL** [comment]
That sounds like fun. Not. I'll see what happens.

Hey, I couldn't checkout the Indra 670G branch from android studio and had to manually download and import. Is there a setting that needs to change?

**Comment by Pogman** [comment]
You may need to update AS and it's plugins but there's no particular special setting that I know of.

**Comment by YYGIRL** [comment]
Hmmm, OK. I could see all the other branches, just not that one. Weird.

**Comment by YYGIRL** [comment]
OK, my fork was f*cked. So redeployed fork. Rebuilt with Indra 670G branch. Turned on extended errors. Restarted phone and replugged in the meter. Still getting same error. Now says:

"Communication Error: Pump sent a NAK(304:0A) response (ReadHistoryRequestMessage)"

It's always connecting on channel 17, if that matters.

**Comment by Pogman** [comment]
Is your 670G a new pump with less then 90 days of use?

There is a bug related to that and there is a fix coming soon for it.

**Comment by YYGIRL** [comment]
Yes it is. OK, sounds good. I'll delete this. Thank you so much for the help!
