### ISSUE TITLE
Uploading to nightscount was unsuccessful

### ISSUE THREAD

**Issue by tonypartridge** [pazaan/600SeriesAndroidUploader#177]
#### Your Environment

* Uploader Version Number: 0.5.1-40-gb1861d4
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Nokia TA-1020
* Android Version Number (e.g. use 4.4 for 4.4.4): 7.1.1
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wifi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): latest

So everything seems to work fine, using the latest India branch, hoping to get past data into the mongodb via nightscout upload. but I keep getting:

Uploading to nightscount was unsuccessful

Yet my live readings are fine, any ideas how I can debug this? new to android development but have it working to install.

**Comment by Pogman** [comment]
restart your Azure or Heroku Nightscout site

**Comment by tonypartridge** [comment]
Hello @Pogman done, no change?

The site still gets the live current data and stores it. Just not the CGM history data. i.e. say a week ago, I've set it to 90Days.

**Comment by Pogman** [comment]
Usually ff you get "Uploading to nightscount was unsuccessful" it won't upload anything at all - it's NS having an issue.

If your looking at your reports you may need to clear your browser cache first. Also it can take some time for historical data to be read and sent as it only gets 1 to 2 days per poll and limits uploads to NS.

**Comment by tonypartridge** [comment]
So looking at the logs more closely I see:

```
 Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) PumpHistoryHandler CGM records to upload: 5346 limit: 400
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) PumpHistoryHandler BOLUS records to upload: 520 limit: 20
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) PumpHistoryHandler BASAL records to upload: 118 limit: 20
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) PumpHistoryHandler BG records to upload: 296 limit: 20
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) PumpHistoryHandler PROFILE records to upload: 4 limit: 20
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) PumpHistoryHandler MISC records to upload: 35 limit: 20
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) PumpHistoryHandler total records to upload: 484
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) NightscoutUploadService Starting upload of 687 record using a REST API
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) libc-netbsd getaddrinfo: tpiomnightscout.herokuapp.com get result from proxy gai_error = 7
Thu Jan 18 2018 13:17:52 GMT+0000 (GMT) NightscoutUploadService ERROR uploading data!!!!!
```

And my heroku app has no treatments stored. Only BG Readings...

**Comment by tonypartridge** [comment]
Whoops missed of that it also outputs:

 Thu Jan 18 2018 13:27:50 GMT+0000 (GMT) MasterService Message Receiver: {ion_alert_circled} Error uploading: Unable to resolve host "tpiomnightscout.herokuapp.com": No address associated with hostname 
 Thu Jan 18 2018 13:27:50 GMT+0000 (GMT) MasterService Message Receiver: {ion_alert_circled} Error uploading: Unable to resolve host "tpiomnightscout.herokuapp.com": No address associated with hostname
Thu Jan 18 2018 13:27:50 GMT+0000 (GMT) UserLogMessage addMessage: {ion_alert_circled} Error uploading: Unable to resolve host "tpiomnightscout.herokuapp.com": No address associated with hostname
Thu Jan 18 2018 13:27:50 GMT+0000 (GMT) PumpHistoryHandler close history handler
Thu Jan 18 2018 13:27:50 GMT+0000 (GMT) ToolKit releaseWakeLock: WakeLock{968dfda held=true, refCount=1}
Thu Jan 18 2018 13:27:50 GMT+0000 (GMT) ActivityThread SVC-Destroying service info.nightscout.android.upload.nightscout.NightscoutUploadService@8593afc
Thu Jan 18 2018 13:27:50 GMT+0000 (GMT) NightscoutUploadService onDestroy called
Thu Jan 18 2018 13:32:27 GMT+0000 (GMT) libc-netbsd getaddrinfo: app.bugfender.com get result from proxy gai_error = 7
Thu Jan 18 2018 13:32:37 GMT+0000 (GMT) ActivityThread BDC-Calling onReceive: intent=Intent { flg=0x14 cmp=info.nightscout.android/.medtronic.service.MedtronicCnlAlarmReceiver (has extras) }, receiver=info.nightscout.android.medtronic.service.MedtronicCnlAlarmReceiver@277ec0b 

After Error Uploading Data

**Comment by pazaan** [comment]
Can you get to that URL in a browser on your phone?

**Comment by tonypartridge** [comment]
Certainly can indeed.

**Comment by tonypartridge** [comment]
It would be handy if we could have a button to 'Start upload' so I could force an upload.

**Comment by pazaan** [comment]
I can see data on that site. I expect that it's still trying to upload history.

**Comment by Pogman** [comment]
how old is your pump? there are some bugs resolved that related to pumps with <90 days use. Saying that though that error is the android api saying it can't connect to that address and usually means your offline or have a patchy connection.

**Comment by tonypartridge** [comment]
Pump is a year or two old, I've got a new one to plug in tomorrow. 

Phone is also new, but no simcard. On strong WIFI.

Full log from earlier today here: 
https://www.dropbox.com/s/2jhfo6o4c2jwsgg/session_1284783273.txt?dl=0

I've just removed xDrip incase they were somehow clashing the upload.

**Comment by tonypartridge** [comment]
I’ve just put my sim into it invade the history upload is trying over the phone network opposed to WiFi, but then went and took a blood test too lol, so it’s calibrating now. Will check back in the morning and if it’s still a no goer I’ll start learning how to use Android Debugger, looks very similar to phpStorm anyhow.

**Comment by tonypartridge** [comment]
Nope still failing.

**Comment by tonypartridge** [comment]
@Pogman I was under the impression India branch was needed for pulling past history data?

**Comment by pazaan** [comment]
This is a pre-release, so it's being worked on by developers. It's not something that we're supporting yet.

**Comment by tonypartridge** [comment]
Ok, I’ll work on it tomorrow see if I fathom it out. Seems mainly there just a few bugs.

**Comment by Pogman** [comment]
It would be helpful to know if v5.1 works on your phone as the log shows no issues as such with this version.

**Comment by tonypartridge** [comment]
Why? The India version works as the 5.1 would, pushing data to Nightscout is fine.

It’s when trying to push history and non bg data it fails, looking at the code it’s not been fully implemented to push to the RESTAPI yet and and is in development stage as per the branch name 😂.

Will have a tinker tomorrow pushing to a local docker container.

**Comment by tonypartridge** [comment]
Ok, ran it through the debugger it’s because careportal was not enabled on nightscout. We need to have exception messages as to why it failed. Even an error code would work. Unless we only want to focus on devs :-)
