### ISSUE TITLE
Indra 6.0 Uploader Crashes after showing „Profiles Clan Be uploaded from the main menu

### ISSUE THREAD

**Issue by Alines640g** [pazaan/600SeriesAndroidUploader#185]
Hi,

I used the 5.1 uploader without any problems.
As I dated it up to the new version the following accurs:

Nightscout Site is available
Connecting to contour next link
Connnected on channel 20 Rssi 22%
Sgv 90 at 21:21:32 Pump +400sec
History cgm backfill 
Cgm history requested 
Pump History requested
Next Polo due to...
No basal Profile has been uploaded
Profiles can Be uploaded from the main menu 
Then it crashes with the call the App has been stopped, relaunch it?
If i do this the same happens again 🤔.
I would Be happy if someone could help me 😀.
Kind regards, Jürgen

#### Your Environment

* Uploader Version Number:6.0
* Your Android Phone Model Name (e.g. Samsung J1 Ace):Samsung A3 and s6 Edge 
* Android Version Number (e.g. use 4.4 for 4.4.4):8.1
* Network Connection at the time the issue occurred (Wi-Fi, Mobile):wifi and mobile 
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):newest version, Master Branch

#### Brief Explanation of Issue
the app crashes 

#### Steps to Reproduce (for bugs)

1.if i Start the app 
2.
3.
4.

#### Severity Score
2-3

**Comment by Pogman** [comment]
Did you rename any of the basal patterns in the options?

**Comment by Alines640g** [comment]
Hi,
No i didn‘t. Should i?
Following my profile settings.

**Comment by Pogman** [comment]
An updated version will be released shortly.

**Comment by Alines640g** [comment]
Thank you. You‘re doing a great job and have an increadible impact to the relativ normal life my 3 year old daughter (t1)has.

**Comment by Pogman** [comment]
closing fixed and released in v0.6.1
