### ISSUE TITLE
Problems uploading to NS Carbs

### ISSUE THREAD

**Issue by amspoke** [pazaan/600SeriesAndroidUploader#186]
Hi,

I'm using INDRA reléase, and i have found a problema when the system uploads the CARB used on the bolus wizard. Here we use 10grams per each ration, but the system seems to calculate it using 15grams (i think is the measure you use on USA), is this configurable, or is it a bug?

Thanks!

**Comment by Pogman** [comment]
The pump actually works internally as 15G per exchange and NS has no concept of exchanges. There's option in to adjust coming soon.

*** fixed in v6.1

**Comment by Pogman** [comment]
closing fixed and released in v0.6.1
