### ISSUE TITLE
Question regarding History Sync Feature and data created from other sources.

### ISSUE THREAD

**Issue by aboncher** [pazaan/600SeriesAndroidUploader#187]
Hey, apologies as this is partially a request to fully understand a new feature, and not necessarily an issue per se.

Under the History Sync option, there is a note "This will clear and refresh data as needed."  What happens when data is cleared? Can it erase events that it didn't create?

The reason I ask is I would like to upload data from a Freestyle Libre to the same NS website, to compare  sensors. Would a History sync from my 600 series uploader have the potential to erase data created by my Freestyle uploader?

I'm happy to test out and see for myself, but I won't get a sensor until Monday.

* Uploader Version Number: 0.6.0

#### Brief Explanation of Issue
See request above.

#### Uploader Error Code
N/A

#### Steps to Reproduce (for bugs)
N/A

#### Severity Score
1

**Comment by Pogman** [comment]
Yes it will "clear and refresh" by the number of days selected. If unselected it will only engage the new features from the start time of the of new version. This is for data integrity and 30/60/90 days of previous pump history will reflect that period exactly as it happened. It will keep any notes that were entered in that period.

**Comment by aboncher** [comment]
Thanks for the clarification
