### ISSUE TITLE
token-based access: works, but nags that it wouldn't

### ISSUE THREAD

**Issue by th122** [pazaan/600SeriesAndroidUploader#188]
Default disclaimer: I'm in love with indra, you guys are awesome! 

#### Your Environment

* 0.6.0 / indra / indra-rc1
* moto G5
* Android V7
* Wi-Fi
* 0.10.3-dev-20171205 head b27950f2

#### Brief Explanation of Issue
indra warns to set AUTH_DEFAULT_ROLES even if there's a token-based acces with matching permissions of devicestatus-upload and readable. This seems to be cosmetic only, since data gets uploaded successfully

#### Steps to Reproduce (for bugs)

1. set up an access token with permissions devicestatus-upload, readable	
2. set the upload link to contain the access token (ignoring the API secret)
`https://<host>.ns.10be.de:<port>/?token=indra-0...`
3. Watch log giving instructions on how to set authDefaultRoles on azure/Heroku :)

#### Severity Score

1 - This seems to be cosmetic only, since data does get uploaded and backfilled successfully. (sgv and basal changes and pump profile, so it's not xDrip or AndroidAPS sneaking in what they got by xDrip broadcast)

**Comment by Pogman** [comment]
Yep this used to be an issue that would block any uploading but got changed in NS to use a default of 'readable' and now AUTH_DEFAULT_ROLES acts only as a user override.

*** this check removed in v6.1

**Comment by Pogman** [comment]
closing fixed and released in v0.6.1
