### ISSUE TITLE
Insert BG as CGM not working while pump battery is low.

### ISSUE THREAD

**Issue by th122** [pazaan/600SeriesAndroidUploader#193]
Tried to activate "Insert BG as CGM" as an experiment to get a current value into xDrip during the warm-up phase of the sensor, but nothing transpired. 

_Could this be due to not asking for history while battery is low?_ 
(Battery was reported as low just after arriving at work, hope it'll last a little bit longer. )

#### Your Environment

* 0.6.0 / indra 
* moto G5
* Android V7
* Wi-Fi
* 0.10.3-dev-20171205 head b27950f2

#### Uploader Log excerpt

(typed from screen)
- ... connected
- ... sensor in warm up phase
- ... history: recent finger bg
- ... next poll due...
- ... Warning: pump battery is low. Poll intervall increased, history and backfill processing disabled.

btw: is there a way to access the log file-wise? The messages don't seem to trickle into system logs.

#### Steps to Reproduce (for bugs)

1. Activated "Insert BG as CGM" setting
2. disconnected meter, took bg reading, reconnected meter
3. Uploader detected reconnected meter and initiated read
4. recent BR read discovered, but no value displayed or communicated anywhere.

#### Severity Score

1 -- While the feature is great, expecially when there's no sensor readings (or no sensor at all) it's hard to miss a bg reading, so the only impact is on data analysis, not on care.

**Comment by Pogman** [comment]
This is by design to reduce the use of the pump battery.

You can override this by setting the low battery poll period to the same as standard poll period ie. 5 mins.

**Comment by th122** [comment]
Wouldn't that still not get the bg, since it's asked off the pump history, and - as far as I thought- the pump got polled anyway because of the "meter reconnected" event but the historical data didn't get requested to save energy?
In case of low pump battery, maybe asking the meter bg directly instead of the meter bg data as stored in the pump might be an option.
(And given the length of my day at work, I'll gladly let the uploader conserve energy :-}

**Comment by th122** [comment]
Thanks for _that_ warning, I wasn't prepared for sudden battery failures (or rejects)! 
I'll reset the low battery poll and try again, then, thanks!

**Comment by th122** [comment]
Great! yes, with low battery poll at 5 minutes it does retrieve history. It didn"t even detect the BG reading though, this time. (Might be a timing issue: The pump has the BG data with a timestamp of 15:54, the meter got reconnected right after it confirmed "sent", and the reading has a timestamp of 15:53. Subsequent requested polls at 15:55 and 15:58 didn't pick up the BG reading.
I'll give it another try with some more time before reconnecting the meter. Have to be quick, it'll ask for calibration any moment now.

**Comment by th122** [comment]
Didn't work either:
- it did detect the recent finger BG, 
- the history got retrieved, but neither did it display the valueof the finger BG, nor was it sent to nightscout or XDrip.

(Now the pump requested calibration. Of course it asked to snooze the alarm instead of picking up the BG it got sent about 90 seconds ago {-8 )

**Comment by Pogman** [comment]
sounds like the pump dropped it from it's history - or just bad timing. If it's in the history it will show up next time but you might just want to try getting your bg again.
