### ISSUE TITLE
Poor pump battery life after 0.6.0 update

### ISSUE THREAD

**Issue by ireneusz-ptak** [pazaan/600SeriesAndroidUploader#196]
#### Your Environment
0.6.0 uploader
640G pump

#### Brief Explanation of Issue
Great job with the latest update but... the pump battery lasted for 6-7 days, now it's only 2 (reproduced twice).

I've changed the set of data being downloaded from the pump to see if it helps.

#### Steps to Reproduce (for bugs)
1. Change battery in the pump
2. Wait 2 days
3. Low battery

**Comment by Pogman** [comment]
You should use better batteries in the pump ie the best pro batteries available. As as example I get 7 - 10 days on a 640G with an average of 20 history pull ops per day using pro rechargeables. You can look at the userlog to gauge how often it needs to get history. If it's very often it will use more power. Adjust the features you need based on this or turn them off via the system settings.

**Comment by ireneusz-ptak** [comment]
I'm using the same batteries as before, but it seems the uploader is not the problem. Even after the downgrade to v5 the problem persists.

**Comment by ireneusz-ptak** [comment]
Just a small follow-up for anyone visiting this thread - pump was replaced by producer and working time increased from 3 to 14 days on lithium batteries.

**Comment by Pogman** [comment]
:+1:

**Comment by volkerrichert** [comment]
hm, maybe we have to change it, too. We just have 4 Days on lithium and 6 or 7 on a those industrial AAs
