### ISSUE TITLE
Basal values incorrect when doing extended bolus (Both in Dual wave & Square wave)

### ISSUE THREAD

**Issue by ekazum** [pazaan/600SeriesAndroidUploader#203]
When using extended bolus (dual wave - we use it allot with our 7 yo) Basal values seem incorrect
I see it showing C:2.xxx , but we never ever reach 2U/hour...
It didn't bother me till now but just started using AndroidAPS and it's affecting it (Raised to Milos Kozak as well on AndroidAPS group in FB

#### Your Environment

* Uploader Version Number: Indra 0.6.1
* Your Android Phone Model Name : Samsung Galaxy S6
* Android Version Number (e.g. use 4.4 for 4.4.4): 7.0
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wifi
* (if relevant) Nightscout website version :0.10.2-release-20171201 master
Pump: Medtronic 640G

#### Brief Explanation of Issue
Whenever using dual wave , Basal values look incorrect
Instead of showing the Base Bazal + Extended bolus, it shows C:2.XXX , where XXX is always the base bazal (e.g. 2.150)
However this is wrong since our extended bolus is usually no more than 1U over 1.5-2 hours
Now the more serious problem is that when I try to use AndroidAPS, it seems it affects IOB calculations and hence the recommendations...

#### Uploader Error Code
N/A

#### Steps to Reproduce (for bugs)

1. Set Bazal to 0.1U/hour
1. Do extended Bolus (D) o 0.8U
2. divide 50% / 50%
3. Set time to 2 hours
4. See Basal rate in nightscout (It should be 0.3U/hour. instead it shows 2.100U/hour)
5. As advanced step - Connect AndroidAPS to NS, see IOB calculation, it goes totally wrong!

#### Severity Score

It depends if you use open loop or not
2 - If you use nightscout only for viewing monitoring 
5 - If you use AndroidAPS as open loop, it seriously affect Insulin dose

![untitled](https://user-images.githubusercontent.com/33403132/36646824-6f411510-1a85-11e8-88c9-27ba60b19370.jpg)

**Comment by Pogman** [comment]
Any issues like this are to do with nightscout itself as the data sent is correct afaik. This would need an issue reported there.

**Comment by ekazum** [comment]
I will open an issue there, but just wondering - If it's nightscout, then problem should be seen with all uploaders (e.g. Dexcom) not only 600-series right?

**Comment by Pogman** [comment]
Dexcom only does cgm. You should be able to cause the same issue by doing a manual combo bolus via the NS website interface.

**Comment by Pogman** [comment]
I've been trying to recreate this but it seems to work ok in NS for me. The picture you posted may be confusing the issue in that there looks like it has a dual (split combo) bolus and later a square (0%/100% combo) bolus - NS is likely reporting the basal from that square bolus and not the dual one that you have highlighted. Perhaps you could try and find some more clear examples of the problem just to be sure.

Also just to note: the uploader does not create the basal pill value, it comes from the profile stored in NS + info from a treatment ie temp basal or combo bolus.

**Comment by ekazum** [comment]
Thanks, the picture may be confusing since we had to replace tube in the middle of the extended bolus....
However it is consistent, I will upload another picture this evening
It might be that NS is displaying it wrong, will try also this direction

**Comment by ekazum** [comment]
This is the MongoDB record of the shown extended bolus - NS is taking the value 2 is taken from "relative" field in the record, I checked the code in getTempBasal function in profilefunctions.js 
{
    "_id": {
        "$oid": "5a92ffee8bbbf0e2f72a524f"
    },
    "created_at": "2018-02-25T20:17:59+02:00",
    "duration": 60,
    "enteredinsulin": "0.15",
    "eventType": "Combo Bolus",
    "key600": "BOLUS807C4630",
    "relative": 2,
    "splitExt": "100",
    "splitNow": "0"
}

But the problem is that it is always 2 when I do dual wave bolus. 
Is this field suppose to be somekind of ratio?

**Comment by Pogman** [comment]
You might be on to something there. I will look into it, thanks.

**Comment by ekazum** [comment]
My take is that this should be a calculation similar like the following -
relative = (squareProgrammedAmount/squareProgrammedDuration)*60

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
