### ISSUE TITLE
Support for 5xx pumps?

### ISSUE THREAD

**Issue by imakeinterfaces** [pazaan/600SeriesAndroidUploader#205]
Now that the medtronic connect uploader is discontinued, this setup could be very useful for 5xx users. Does anyone know if the data format is different or if there are any hardware differences between the contour next link issued with the 500 and 600 series pumps?

**Comment by andyrozman** [comment]
Yes format of the messages is much different, but I am sure that developers here would be able to change it. I have been experimenting with it a little, for my own project. I can share my code with any of devs here, but I was stopped in middle of my work, so while my code is ready to be tested, I haven't tested it yet (so it might have some errors in it).

**Comment by imakeinterfaces** [comment]
@andyrozman If you can share it i'd appreciate it! I can help work on parsing it.

**Comment by imakeinterfaces** [comment]
@andyrozman Oh wait, can medtronic uploader already do this? https://github.com/arbox0/MedtronicUploader

**Comment by pazaan** [comment]
Yes, that's the uploader for the 5/7 series protocol.
