### ISSUE TITLE
Wrong units string uploaded

### ISSUE THREAD

**Issue by AdrianLxM** [pazaan/600SeriesAndroidUploader#207]
In the Profiles/ProfileSwitches, "mgdl" is uploaded to Nightscout instead of "mg/dl". This will cause other systems that receive the data to default to mmol/l.

#### Severity Score
5 for now - can lead to wrong recommendations of bolus calculator and closed/open loop systems. (We should at the same time make other apps like AndroidAPS more tolerant to non-standard Strings).

**Comment by Pogman** [comment]
OK but... the NS docs state "mmol" or "mgdl" for profile use:
![ns-api-profiles](https://user-images.githubusercontent.com/7413594/37042643-c63ded34-2156-11e8-9b1a-3b734cea4072.JPG)

*sigh* so does this actually need to be changed here?

**Comment by Pogman** [comment]
BTW the "BG Check" treatment we send to NS contains "mg/dl" or "mmol" for the units.

I would tend to agree with you that a reader should probably for check both versions to be on the safe side.

I'm happy to tag this for the uploader to send "mg/dl" in the next version, just don't want to break something else given the docs.

**Comment by AdrianLxM** [comment]
AndroidAPS sends `mg/dl` "for ages" (since early 2016) now and it works very well.
It also receives and compares it with the profiles generated within Nightscout and those send "mg/dl".

So I assume internally Nightscout uses "mg/dl" and the documentation is mistaken. 
In other parts of the documentation like for `DISPLAY_UNITS` it also want `mg/dl` and `mmol` (without the "per litre")

**Comment by MilosKozak** [comment]
mg/dl should be used for NS upload

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
