### ISSUE TITLE
Checking the possibility of a one-poll-functionality

### ISSUE THREAD

**Issue by er0780** [pazaan/600SeriesAndroidUploader#209]
I want to ask for a litte "reprogramming". Our little one is said to go to child care. The nurses want to use your uploader in combination with the Contour Next Link. But they will not be near our child at all times. So they will not stand next to him until the next poll is done. They would like to stand next to him, push a button and read out the data immediately.
I know, that there is a "read out data" function in the menu.
But, and this is a question, would you be so kind to program it that way, the a "bigger" button is on the main screen of your uploader (there where the logging is collected), please?

**Comment by er0780** [comment]
Lennart answered:
There used to be a button there, and it was moved to the menu by request, and to match Material Design patterns (as it is generally an infrequently used button).
So it’s possible to add a button, but I don’t think I’d want to add that as a UI element that’s always there for everyone.
And then there’s the question of whether to add it to the main logging area, or as part of the menu bar at the top.
Are you open a ticket on GitHub so that we can further the discussion?

**Comment by er0780** [comment]
Dear Lennart,
 thanks for reply!
You are absolutely right. The suggestion I made is just an individual one. We want to use your Uploader as a "non-stinging glucometer". Our child is not willing to wear a mobile connected to the Contour Next Link all the time ... he is just too small.

May be there should be an entry in the menu that allows to decide where the poll-button is located? ;)

Kind regards.

**Comment by Pogman** [comment]
@er0780 This is a 'curious' request for your use case. Why not just have the care person look at the pump screen as the live SG reading will always be shown there?

The uploader device just needs to be close and if it's generally in the same room and not overly blocked it should be picking up data whenever in range.

**Comment by er0780** [comment]
@Pogman 
No, it is not. ;)
1. The persons in the child care are child care nurses without any medical background. By law they do not have to do anything with a child having Diabetes. If they have a look on the blood sugar values it is just a personal kindness. So we cannot demand, we have to ask for.

2. The child care cares for about 100 children. They have a common dining room. And the group of our child is located in 2 room which they can use at any time. Each of this rooms has about 30 m^2.

**Comment by Pogman** [comment]
Ok but just the very nature of bringing the device into the same room as the child will likely have done the reading automatically without needing interaction. A manual poll will sometimes be deferred, sometimes up to 60 seconds, to avoid pump/sensor radio clashes and a reading may take some time to complete anyhow.

I'm still on the curious end here :) as I would be wary of leaving a T1 child with any carers that did not understand their needs and being able to do finger bg's, boluses, deal with hypos etc.

**Comment by Pogman** [comment]
I forgot an additional tip for use when a device is often in/out of range: In the uploader settings enable the 'double polling if pump is away' - this will attempt to poll every 2.5 minutes and reduce the need to wait even more.

**Comment by Pogman** [comment]
Actually have a potential solution to this without the need for any UI mods:

If the uploader has not gotten a reading at the last poll time (greater then 5 minutes passed) and the device is picked up and the app opened, it will automatically engage a poll at that moment without any delay ie. will not wait until the next scheduled poll time . No button pressing required.

**Comment by er0780** [comment]
Both comments / ideas are interesting. I will check this!
But I will be open for further discussions.

As a comment: Child care nurses care for the children. For medical issues we have medical nurses. The are independent of the child care and self-reliant. They come around for the meals, handle blood glucose sugars, calculations and bolus.
This is our system. We have to accept or ... nothing.

**Comment by er0780** [comment]
Fedback:
Both opportunites you mentioned work, but they are not always working. So it is fine but not perfect.

**Comment by Pogman** [comment]
The last item I mentioned is only a proposed enhancement and is not currently part of the uploader.

RE: If the uploader has not gotten a reading at the last poll time (greater then 5 minutes passed) and the device is picked up and the app opened, it will automatically engage a poll at that moment without any delay ie. will not wait until the next scheduled poll time . No button pressing required.

**Comment by er0780** [comment]
Ah. But sometimes it works.
I tried again ... It is only working when running the app and connecting the Contour Next Link to the mobile.

**Comment by Pogman** [comment]
It does, when cnl is reconnected or app has been started from being fully closed or phone is restarted.

**Comment by er0780** [comment]
Exact.

**Comment by pazaan** [comment]
Will resolve this by running "Get Data now" on app open. This seems like a reasonable generic implementation, since when anyone opens the app, they would want to see the most recent data.

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
