### ISSUE TITLE
Add basal info uploading to Nightscout

### ISSUE THREAD

**Issue by pazaan** [pazaan/600SeriesAndroidUploader#21]
Send:
- Basal patterns
- Active basal pattern from the status message
- Temp basals from the status message
- LGS temp basal from the status message, with a note that it was a LGS

**Comment by pazaan** [comment]
Mock for LGS note.
<img width="600" alt="lgs mock" src="https://cloud.githubusercontent.com/assets/96943/15380747/704fa3ee-1dbc-11e6-925b-408c7695a948.png">

**Comment by Bal00** [comment]
Active pattern would be a great enhancement but should upload periodically (or even better, be stored on phone and only transmitted to NS when a change is detected) in order to minimise data use..

**Comment by William1444** [comment]
👍

**Comment by Pogman** [comment]
closing - feature available on 0.6+
