### ISSUE TITLE
IC without decimal place

### ISSUE THREAD

**Issue by st0ber** [pazaan/600SeriesAndroidUploader#215]
If you enter the value in the pump MM640g (in german "KH factor" a value with decimal place (eg 7.5),
after transferring the profile to Nightscout (in German "insulin / carbohydrate ratio (I: KH) [g]:") is only the whole value (without decimal place).
![img_20180403_115359_836](https://user-images.githubusercontent.com/32514747/38242705-c07f0316-3735-11e8-9657-6e62baa6e267.jpg)

**Comment by Pogman** [comment]
Mmmm might have missed that the pump can use fractional carb amounts there.

Looking at the pump, it goes from 1.0 to 9.9 in .1 g/U and when >10 g/U it increases by 1.

The Bolus Wizard seems to only allow whole carb amounts ie. 1g increasing by 1 each increment.

**Comment by Pogman** [comment]
I also can't quite remember but Nightscout profiles may only handle non-fractional carb ratio amounts. This would need checking.

**Comment by st0ber** [comment]
I can Input the value 7.5 and save it with sucess. I use only the Bolus Wizard in my Pump.
