### ISSUE TITLE
Sensor AGE and Battery AGE 

### ISSUE THREAD

**Issue by st0ber** [pazaan/600SeriesAndroidUploader#218]
In order to see the change of the battery, as well as the change of the sensor in AAPS, one would have to change the event type from "Note" to "Pump Battery Change" and change the event type when changing the sensor to "Sensor Change". Would that be possible to provide compatibility with AAPS?
![38515646-1805221a-3c35-11e8-9204-1b20a623bd54](https://user-images.githubusercontent.com/32514747/38537838-2a2b7f1e-3c91-11e8-9ba0-0b401116e3c0.png)

**Comment by st0ber** [comment]
I have just seen that with the profile switch, only the event type "Note" is set and not the event type "Profile Switch".

**Comment by Pogman** [comment]
I'll have a look at the sensor and battery requests.

Profile Switch is always sent to NS for a pattern change pump event.

**Comment by st0ber** [comment]
Any news on this?

**Comment by Pogman** [comment]
It will be in the next version but I don't have a date for that. If you want it now and can compile the code yourself it's a simple change of the type that's sent to NS.

Make this: "Sensor Change"

https://github.com/pazaan/600SeriesAndroidUploader/blob/07c55a4afa8a8245495aed896209846a4e9a5d22/app/src/main/java/info/nightscout/android/model/medtronicNg/PumpHistoryMisc.java#L55

Make this: "Pump Battery Change"

https://github.com/pazaan/600SeriesAndroidUploader/blob/07c55a4afa8a8245495aed896209846a4e9a5d22/app/src/main/java/info/nightscout/android/model/medtronicNg/PumpHistoryMisc.java#L58

**Comment by st0ber** [comment]
Thanks, this is great. I try to compile it by myself.
Thank you Pogman
