### ISSUE TITLE
Alarms / Events / Notifications

### ISSUE THREAD

**Issue by Pogman** [pazaan/600SeriesAndroidUploader#219]
Direct support for Pushover and IFTTT from the uploader to handle pump specific alarms and alerts.

Users, parents in particular seem to be having the hardest time and the with most need for these alerts and Nightscout does not handle them well or at all or is very awkward for a non-tech user to set up. It doesn't help that a browser is just not reliable for alerts specially on mobile devices.

Thread here is to get a placeholder and a starting point for this feature tentatively targeting v0.8.0

**Comment by cfaagaard** [comment]
I agree that NS-website is not the best for alarms and alerts. I have turned those off.
I personally use xdrip+ for alarms (high/low/missing data) as a "xdrip+ sync follower". 

**Configuration of pushover/IFTTT/Flow on the uploader for non-tech-users:**

When it comes setting up alarms/alerts for non-tech users, maybe pushover/ifttt/flow etc is not the best choice.
Using pushover/ifttt/flow I also think there are some delays in the services. I think I read something about this lately on facebook.
Furthermore if you have multiple uploaders you need to set it up on each uploader.

If you want alarms/alerts functionality in the uploader, I think you should make a configurable "mode" for the application:
"Uploader-mode": like today, where the application uploads data.
"follower-mode": where you can configure different alarmsettings and get alarms/alerts. Data comes from NS-website. 
It should be possible to be in both "modes" on one uploader. 

But again, it seems the alarm/alert-functionality is already in place in other apps. (and you will only support android-users/followers/parents).

But support for "direct" pushover/ifttt/flow in the uploader: I can see other user scenarios where this could be very good. If you want to send data not only to nightscout, but for example also a spreadsheet on google drive. Or when a sensor-replacement-event happened you want to create a calendar-entry (+ 6 days from the event) in your google calendar (and insulin-change-event +3 days).

(disclaimer: I have not tried the "maker" functionality on NS-website :-))

**Comment by Pogman** [comment]
Other apps do not provide anything related to pump specific alerts and alarms. There is a need for many that the alert that shows on the pump to be shown to a follower on any device/os. Very specifically the exact pump alerts ie "pump has dropped out of auto mode due to ongoing high sg" and all the obvious ones as set on the pump for lows highs etc. 

I had a very brief look at Pushover and it is very simple for a user to set up. Just download the app to ios/android add email + password for an account. Add email + pass to uploader and the user is done. It needs to be this simple and just work. How much of a lag is there with delivering messages?

**Comment by cfaagaard** [comment]
I agree. No other app has the detail level that you are talking about. 

I have just tested pushover (with postman) and I see no delay. 

You need to create an account AND a pushover application. Then you use the user-key (from the account) and the application-token (from the pushover application) in the json. So the user-key and application-token should be the settingParameters. (and it costs $5 after 7 days - one lifetime fee)

**Comment by Pogman** [comment]
Yeah I'm liking what I see with Pushover for this. Just seen that images can be pushed too... mmmm sgv graph via pushover maybe.

**Comment by Pogman** [comment]
Prototype going well to gauge it's use and effectiveness. This is a bit of a 2 parter, the Pushover support and that it will use the alarm codes from the pump and will need help to get the text for as many of these as we can. To that end the pump alerts will be sent to NS as notifications and tagged with the alert code ie "Pump Alert: Bolus Not Delivered #567" or "Pump Alert: unknown #123". This makes it real easy to look at a NS report for the unknowns and read the alert at the time on the pump. Carelink itself only provides partial data and none at all for the 670G. Many of these are already known based on my use and I think most will be found by beta testers.

Having the exact pump alerts sent to NS is very nice in itself I think and with easy push to any device, iOS Android Mac PC or any browser this should be a killer feature for parents.

![screenshot_20180417-213538](https://user-images.githubusercontent.com/7413594/38936187-2ae44cc8-4318-11e8-9e57-2b5459c2ab8a.png)

![ns-pushover-watch](https://user-images.githubusercontent.com/7413594/38936202-32240708-4318-11e8-8220-8d72928da449.jpg)

![ns-alert-test-1](https://user-images.githubusercontent.com/7413594/38936227-3d55f3ca-4318-11e8-9c97-35001efd7cdd.JPG)

![ns-pushover-settings](https://user-images.githubusercontent.com/7413594/38936232-413ce5f2-4318-11e8-8759-19aa2ba68dd2.JPG)

**Comment by Pogman** [comment]
Desktop client (OpenSource Pullover on Git):

![ns-pushover-desktop](https://user-images.githubusercontent.com/7413594/39002814-46417e62-43f1-11e8-8114-9c1b4a44f340.jpg)

**Comment by Pogman** [comment]
Pullover also does a pop-up as a new message is pushed:
![ns-pushover-desktop-popup](https://user-images.githubusercontent.com/7413594/39003405-b32b69a6-43f2-11e8-87e1-a65a53805324.jpg)

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
