### ISSUE TITLE
Question: Which data transfered Uploader to xDrip+

### ISSUE THREAD

**Issue by st0ber** [pazaan/600SeriesAndroidUploader#224]
Which data is transferred from the uploader to xDrip +?

I ask because if I enter a Temporary Basal rate which is sent to Nightscout, but in the Offline (Open) Loop they do not arrive at AndroidAPS.

**Comment by Pogman** [comment]
Sensor data only.

**Comment by st0ber** [comment]
Thank you for the answer Pogman

**Comment by Pogman** [comment]
I'll have a closer look at some point to better integration with AndroidAPS but as I don;t use it I don't know what's involved.

If there is a local broadcast api for useful data a sender system could be added.

The thing to be wary of is that pump data can change after the fact - like partial boluses etc.

**Comment by st0ber** [comment]
Thank you for your help. It would be great if there is a solution.

**Comment by st0ber** [comment]
I do not really know anything about programming, but would that work with xDrip + in collaboration with @jamorham and its local web services?

https://github.com/NightscoutFoundation/xDrip/blob/master/Documentation/technical/Local_Web_Services.md

**Comment by volkerrichert** [comment]
in current integration was done by @jamorham . See https://github.com/pazaan/600SeriesAndroidUploader/pull/84

**Comment by Pogman** [comment]
Quick look there at the current version of xDrip and it looks like it has very simple support for treatments. I only see carb/bolus entry type and nothing for basals of any type.

@st0ber that local web services link is for queries so that a smart watch or other app can get data locally - really just for sgv.
