### ISSUE TITLE
USB Connection Error. Is the contour next link plugged in?

### ISSUE THREAD

**Issue by maxtatreau** [pazaan/600SeriesAndroidUploader#227]
#### Your Environment

* Uploader Version Number: 600-series-ns-uploader.apk
* Your Android Phone Model Name (e.g. Samsung J1 Ace): MOTO g4
* Android Version Number (e.g. use 4.4 for 4.4.4): 7.0
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): wifi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):

#### Brief Explanation of Issue
I plugged in the OTG cable to connect phone with contour next link meter and this error message comes up: USB Connection error. Is the contour next link plugged in?

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Severity Score
 3

**Comment by pazaan** [comment]
Have you run [Easy OTG Checker](https://play.google.com/store/apps/details?id=com.kjarvel.easyotgchecker) or a similar app to confirm that USB OTG works on your phone?
Did you get a permission dialog for USB access when you first plugged in the Contour Next Link?

**Comment by maxtatreau** [comment]
No, I did not get a permission dialog for USB access when I plugged in the meter

**Comment by pazaan** [comment]
If you plug in another USB device (like a flash drive), does it show up on the phone?

**Comment by maxtatreau** [comment]
No it doesn't, so I'm guessing it's something to do with the cables which are brand new from Amazon.

**Comment by pazaan** [comment]
It would either be the cable, or the USB host mode needs to be enabled on the phone somewhere.

**Comment by pazaan** [comment]
Have you pushed the "Read Data Now" menu item? Is your pump showing a SGV reading?

**Comment by maxtatreau** [comment]
I've pushed read data now several times and nothing comes up, and the pump is showing a SGV reading.

**Comment by maxtatreau** [comment]
Finally got it to come through!! Thanks for taking the time to respond. I appreciate it!

**Comment by pazaan** [comment]
No problem! The first time takes a while to come through, as it's pulling historical data as well. Enjoy!

**Comment by edepalos** [comment]
> Finally got it to come through!! Thanks for taking the time to respond. I appreciate it!

So what was the resolution? I have the same trouble with my son’s uploader?
