### ISSUE TITLE
add 'device' field in 'entries'

### ISSUE THREAD

**Issue by hartlijn** [pazaan/600SeriesAndroidUploader#230]
the 'device' is not filled by uploader.
found by developer of AndroidAPS, which uses Nightscout as BG source.

uploader 0.6.1
android 7.1.2
phone sony xperia sp
nightscout 0.10.3

**Comment by hartlijn** [comment]
it's filled in 'devicestatus' indeed, but not in 'entries'.

**Comment by Pogman** [comment]
ok, will add the 'device' field to 'entries' for the next release

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
