### ISSUE TITLE
Replacement 600 series pumps can cause DB keys to be repeated 

### ISSUE THREAD

**Issue by Pogman** [pazaan/600SeriesAndroidUploader#235]
Each record sent to nightscout contains a "key600" field which is generated from the RTC of the pump event. In general this is always unique and we have the same key even when multiple uploaders are used.

If a pump is replaced the RTC is started again from it's initial value (new pump) and the potential for repeated keys is increased.

While it's very unlikely to actually cause a key clash, if a pump is replaced multiple times and specially in short order the risk increases accordingly.

**Comment by volkerrichert** [comment]
you can add (prefix) the pump-MAC to the key600 to avoid key clashes with new pumps....

**Comment by Pogman** [comment]
Yeah something like that but it has handled with care due to the data already in NS using the original keys.

**Comment by Pogman** [comment]
Additional Info: There is one case from FB noted for this. The user has had 4 replacement pumps and noted odd random gaps in their cgm graph where data was available in the uploader and treatments were getting through to NS in the same period.

Workaround: delete mongoDB data or delete NS site and deploy a new one.

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
