### ISSUE TITLE
Nokia 8 - Update to Android 9 Pie- Nighscout Sync works unstable/unreliable

### ISSUE THREAD

**Issue by deko1** [pazaan/600SeriesAndroidUploader#239]
After updating to Android 9 Pie with Nokia 8 the Nighscout Sync works unstable/unreliable
and hangs often at "Requesting poll now..." but nothing happened
#### Your Environment

* Uploader Version Number: 0.6.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Nokia 8
* Android Version Number (e.g. use 4.4 for 4.4.4): Android 9 Pie
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wi-Fi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 0.10.3 master 20180805

#### Brief Explanation of Issue
 After updating to Android 9 Pie with Nokia 8 the Nighscout Sync works unstable/unreliable
and hangs often at "Requesting poll now..." but nothing happened

#### Uploader Error Code
none 

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.
![screenshot_20181226-141131](https://user-images.githubusercontent.com/46161871/50447089-27ea2700-0919-11e9-9104-a4b4152e4bb8.png)

#### Severity Score
 5

**Comment by pazaan** [comment]
Android 9 is not currently a supported operating system. Although we may be able to add support in the future, it’s not supported now.

**Comment by Pogman** [comment]
issue #202 is similar to this and so it may already be sorted for the next version. Need to check if there are any other differences or permission checks needed for Android 9.

**Comment by Pogman** [comment]
Closed - fixed and available in 0.7.0 release
