### ISSUE TITLE
0.7.0 not working with split screen

### ISSUE THREAD

**Issue by Joachimsee** [pazaan/600SeriesAndroidUploader#255]
I have used v. 0.6.1 together with the navigation app Osmand and I have used split screen without any problems. With the new 0.7.0 it is not possible to reduce the size of the app. See attached screenshots. If i split the screen 50/50 it works well.
![New v 0 7 0](https://user-images.githubusercontent.com/53875941/62689099-72ad4080-b9ca-11e9-9e4d-8d5fb7dd1405.png)
![Older v 0 6 1](https://user-images.githubusercontent.com/53875941/62689111-7771f480-b9ca-11e9-833f-d541e6674d55.png)

**Comment by Pogman** [comment]
Released v0.7.1 has a fix for this. Please report if there is still a problem, thanks.
