### ISSUE TITLE
0.7.0 upload unsuccessful "NaN is not a valid double value"

### ISSUE THREAD

**Issue by mstietencron** [pazaan/600SeriesAndroidUploader#256]
Since updating to 0.7.0 the uploader produces the following error 

> Uploading to nightscout was unsuccessful. NaN is not a valid double value as per JSON specification. To override this behaviour, use GsonBuilder.serializeSpecialFloatingValues() method.

#### Effects:
- all items other than the SG and PUMP are not being uploaded
- most notably the following data is missing:
  - BG
  - Bolus
  - Notifications

#### What I tried so far
- deactivated all upload tasks but SG and Bolus
  - App has uploaded the content once (out of several tries) but other than that, the error is still prevalent. Also I couldn't reproduce this.
- downgraded app to 0.6.1
  - Error disappears, data is successfully uploaded again
- tested on different phone (CAT S40) 
  - Same behaviour, Error still prevalent

#### Environment
* Uploader Version Number: 0.7.0
* Android Phone Model: Unihertz Atom 
* Android Version Number: 8.1
* Network Connection: error prevalent both in cellular as well as wifi
* Nightscout website version: 0.12.3

**Comment by Pogman** [comment]
This is fixed for the v0.7.1 hotfix version, should be out soon. Use v0.6.1 for now.

**Comment by mstietencron** [comment]
Excellent! Thanks a lot for the feedback and your work on this app!!

**Comment by Pogman** [comment]
Released v0.7.1 has a fix for this. Please report if there is still a problem, thanks.
