### ISSUE TITLE
Add finger stick BGs to Nightscout upload (from Status message)

### ISSUE THREAD

**Issue by pazaan** [pazaan/600SeriesAndroidUploader#26]
Currently only CGM values are uploaded. It would be nice to also add manual finger stick entries (as long as they have been entered into the pump).
It's actually possible to pull them straight from the CNLs BGL log (using ASTM).

**Comment by wright-david** [comment]
Recommend to get the data from the **pump** not the CNL.

1. 'unfortunate' people may be using a non-linked BG meter for fingersticks, having sacrificed their only CNL for the uploader stick

2. 'fortunate' young people may have two CNLs - one for school/college and one at home

**Comment by pazaan** [comment]
Good point. Though the fingerstick value in the pump status message is transitory, meaning that we may miss it if we don't poll soon enough. I haven't quite decoded the history log yet, either.

**Comment by wright-david** [comment]
Should we raise an issue (enhancement) for reading that from the history?

**Comment by pazaan** [comment]
I just did a quick check. The instantaneous entry stays around for 10+ minutes, so I'll cover that in this issue. We definitely need to RE the history message. I'm not sure whether we want to raise issues for all new features. If you think we do, then feel free to raise one ;)

**Comment by LittleDMatt** [comment]
Assuming instantaneous entry staying visible for ~10 minutes is linked to 12 minute window of using BG for bolus wizard input

**Comment by pazaan** [comment]
Yes!!! I didn't use a stop watch, and my time check was round about. Thanks for the exact timing :)

**Comment by pazaan** [comment]
Fixed by #143
