### ISSUE TITLE
Any *non-Android* 600Series Uploader?

### ISSUE THREAD

**Issue by steffen-AEI** [pazaan/600SeriesAndroidUploader#260]
I've been unable to locate a non-Android solution for uploading 600 series data to Nightscout, e.g. using a RasPi (which is already there, displaying the NS overview screen) with the NextLink plugged in.
For home-office workers (and all people returning to the same spot frequently) this might be an alternative to using a smartphone, avoiding the obvious charging problem.

Are you aware of such a solution?

Apologies for the noise...

**Comment by HenrikHL** [comment]
I tried this a year ago (https://github.com/pazaan/600SeriesAndroidUploader/issues/210)- never got it to work (I must admit though - I did not put a tremendous amout of work into it). I do have the RasPi and I did boot it with LineageOS - but did not get the 640 uploader to work...
We are still on the phone solution :-(

**Comment by steffen-AEI** [comment]
While there might be a way to replace the battery of an old smartphone with a power supply, thereby overcoming charging issues, a non-Android (and even non-Java) version of this uploader would be highly appreciated.
Thanks for pointing me to the other issue, I'm closing this request, moving there...

**Comment by mattster98** [comment]
I've been using Emteria OS on a RPi3 for several months now with success.  Only issue is the uploader isn't seen if it is plugged in before booting.  You have to unplug/replug once it's up.  Not that big a deal but a problem I'd like to solve.  I opened a thread with Emteria about it and may follow up separately here depending on where that goes.
