### ISSUE TITLE
Uploader does not send data if no Guardian3 sensor used

### ISSUE THREAD

**Issue by kretch** [pazaan/600SeriesAndroidUploader#263]
If I'm just using the 670G without the guardian3 sensor, the uploader doesn't upload data. It would be good for basal,temp basal, CAGE,Carb,Bolus data to be sent to nightscout even if there's no sensor being used (Full disclosure, I used guardian3, got tired of it, and am in the process of switching to dexcom while keeping the 670G).

Comments welcome
Yaron

#### Your Environment

* Uploader Version Number:
* Your Android Phone Model Name (e.g. Samsung J1 Ace):
* Android Version Number (e.g. use 4.4 for 4.4.4):
* Network Connection at the time the issue occurred (Wi-Fi, Mobile):
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by Pogman** [comment]
It should be working and uploading pump events even when the pumps cgm is not in use. Are you using version 0.7.1 of the uploader?

**Comment by kretch** [comment]
Thanks! I'll verify my version
-------- Original message --------From: Pogman <notifications@github.com> Date: 12/22/19  9:16 PM  (GMT-08:00) To: pazaan/600SeriesAndroidUploader <600SeriesAndroidUploader@noreply.github.com> Cc: kretch <yaronkretchmer@gmail.com>, Author <author@noreply.github.com> Subject: Re: [pazaan/600SeriesAndroidUploader] Uploader does not send data if no Guardian3 sensor used (#263) It should be working and uploading pump events even when the pumps cgm is not in use. Are you using version 0.7.1 of the uploader?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pazaan/600SeriesAndroidUploader/issues/263?email_source=notifications\u0026email_token=AB24KMHGFXAMZTKNM3BFPTTQ2BCUNA5CNFSM4J6PJO3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHQHLZY#issuecomment-568358375",
"url": "https://github.com/pazaan/600SeriesAndroidUploader/issues/263?email_source=notifications\u0026email_token=AB24KMHGFXAMZTKNM3BFPTTQ2BCUNA5CNFSM4J6PJO3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHQHLZY#issuecomment-568358375",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kretch** [comment]
Works perfectly with 0.7.1
Thanks
Yaron

**Comment by Pogman** [comment]
Ok great, thanks for letting us know.
