### ISSUE TITLE
Wrong dutch translation for 'ul_ns__help_config_cage'

### ISSUE THREAD

**Issue by stijnbrouwers** [pazaan/600SeriesAndroidUploader#279]
#### Description
The dutch translation for the key 'ul_ns__help_config_cage' shows the wrong plugin name.
It mentions to add 'sage' to the ENABLE variable, while it should be 'cage'

#### Environment
* Uploader Version Number: 0.7.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): One Plus 3
* Android Version Number (e.g. use 4.4 for 4.4.4): 9
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wi-Fi

#### Steps to Reproduce (for bugs)
1. Enable CAGE data gathering in advanced settings
2. The logs on the home page show the wrong translation (Dutch only, I reviewed about 5 other languages which were all correct).

#### Severity Score
1

**Comment by Pogman** [comment]
In version 0.7.3 - thanks.
