### ISSUE TITLE
Pump Alert Code 778, Spanish: Cambiar sensor. No se ha aceptado la segunda calibración. Es necesario colocar un nuevo sensor.

### ISSUE THREAD

**Issue by AlejandroPaula** [pazaan/600SeriesAndroidUploader#282]
#### Your Environment

* Uploader Version Number:
* Your Android Phone Model Name (e.g. Samsung J1 Ace):
* Android Version Number (e.g. use 4.4 for 4.4.4):
* Network Connection at the time the issue occurred (Wi-Fi, Mobile):
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by Pogman** [comment]
This is a missing pump alert code. Not in the 0.7.1 uploader version. Will be included in a future release.  

Notes:

```
    <!-- found as pump alert code #778, uses alert_99101 already localised and translated -->
    <string name="alert_99101" comment="pump alert (see your pump manual) format: heading message|extended message">Change sensor|Second calibration not accepted. Insert new sensor.</string>
```

**Comment by Pogman** [comment]
In version 0.7.3 - thanks.
