### ISSUE TITLE
No se puede comunicar con la bomba

### ISSUE THREAD

**Issue by VanesaRL** [pazaan/600SeriesAndroidUploader#283]
He creado la página en la Heroku. Descargué la aplicación de Nightscout. La configuré pero al conectar el glucómetro Contour Next link al móvil y abrir la app, no es capaz de comunicarse a la bomba.

Bomba: Medtronic 670
Móvil: Xiaomi Mi A2 y Redmi Note 7

**Comment by pazaan** [comment]
Translated:
I have created the page on the Heroku. I downloaded the Nightscout app. I configured it but when I connect the Contour Next link glucometer to the mobile and open the app, it is not able to communicate with the pump.

Pump: Medtronic 670
Mobile: Xiaomi Mi A2 and Redmi Note 7

**Comment by pazaan** [comment]
Are there any log messages on the app?

**Comment by VanesaRL** [comment]
Pone: no se pudo conectar con la bomba. ¿Estás cerca? El problema es que estoy al lado. No se si es cosa del cable OTG y comprar otro

**Comment by VanesaRL** [comment]
Solucionado. Estaba usando un glucómetro que no estaba asociado a la bomba. Todo correcto. Gracias por vuestro tiempo

**Comment by pazaan** [comment]
Great! I'm glad it's working for you now.
