### ISSUE TITLE
Insulin injection event on 640G

### ISSUE THREAD

**Issue by fsamuelm** [pazaan/600SeriesAndroidUploader#286]
# Environment
* Uploader Version Number: v0.7.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Xiaomi Mi8
* Android Version Number (e.g. use 4.4 for 4.4.4): 10
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wi-Fi
* Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): v14.0.6 / head

#### Brief Explanation of Issue
After manually inserting the insulin injection event into the pump, it appears as "exercise" on the nightscout after upload.
And I think that insulin (which enters the nighscout as an exercise), is also not counted as insulin on body (not sure about this point).

#### Severity Score
3

**Comment by Pogman** [comment]
Yep this is a bug - thanks.

**Comment by Pogman** [comment]
notes:

Change PumpHistoryMarker.RECORDTYPE.EXERCISE to PumpHistoryMarker.RECORDTYPE.INJECTION

https://github.com/pazaan/600SeriesAndroidUploader/blob/2aa572c7c807d484702b21949b595bc9ef75d008/app/src/main/java/info/nightscout/android/history/PumpHistoryParser.java#L708-L718

**Comment by fsamuelm** [comment]
Changed and pull requested

**Comment by Pogman** [comment]
In version 0.7.3 - thanks.
