### ISSUE TITLE
Uploading fails with unclear error message

### ISSUE THREAD

**Issue by sjennison** [pazaan/600SeriesAndroidUploader#287]
* Uploader Version Number: 7.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Sonim XP1
* Android Version Number (e.g. use 4.4 for 4.4.4): 8.1.0
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): WiFi & Mobile
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 14.0.6

Uploading fails with `Uploading to nightscout was unsuccessful. length=8`

Enabling error messages adds the additional error message `java.lang.ArrayIndexOutOfBoundsException: length=8`

The logs show `Nightscout site is available`, so I don't think there is any issue with the connection. Using a web browser works fine too.

I'm actively attempting to figure out what's causing this, but even if there's a reason, the error message should probably be made clearer (handle the out of bounds exception somewhere, probably?)

#### Steps to Reproduce (for bugs)
Repro steps aren't clear - this occurred the first time I attempted to use this device

#### Severity Score
4 - completely prevents the upload to Nightscout from working

**Comment by sjennison** [comment]
UPDATE: This is related to uploading profiles - disabling profile upload entirely fixed the issue (not a problem for me, as my 670 is just functioning as a CGM)

**Comment by Pogman** [comment]
It's not expected for this type of bug to be shown in the user log. There is a program log if you want to run logcat of your device and access the app process.

Might be something odd with whatever got read from the pump given your type of use that's not accounted for.

**Comment by sjennison** [comment]
Sure, yeah I'd be happy to help with whatever info you need - just logcat and look for the same Java error?

**Comment by Pogman** [comment]
Yep should be a hard exception where the actual error happened.

This is probably an extremely rare bug due to no reports in years of service. So don't sweat it :)

**Comment by Pogman** [comment]
Fixed in version 0.7.3

**Comment by sjennison** [comment]
Oh hey you found it!

Awesome :)

I turned profiles back on and couldn't get it to happen again, so yea sounds like a weird one-off issue. Thanks!

**Comment by Pogman** [comment]
Cool - thanks for reporting.
