### ISSUE TITLE
USB device (CNL) not recognized neither by Android nor by Windows [SOLVED]

### ISSUE THREAD

**Issue by bchris21** [pazaan/600SeriesAndroidUploader#297]
#### Your Environment
Uploader Version Number: 0.7.3
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Xiaomi Mi6
* Android Version Number (e.g. use 4.4 for 4.4.4): 10
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Tried Both in several mobile phones
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 14.0.7

#### Brief Explanation of Issue
USB is no longer recognized neither by my Android phones, nor my Windows 10 PC and Laptop. CNL is fully functional when measuring BG, sending remote BOLUS etc, but not recognized when plugged in with OTG cable to my Android phones or Windows 10 workstations. In Windows 10 Device Manager i get a yellow exclamation mark. I disabled and re-enabled device, tried to update drivers but nothing did work. I suspect it is purely hardware issue maybe due to not safely ejecting the USB. Is there a way to soft reset the USB or power cycle it? Thanks

#### Uploader Error Code
No specific error.

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Severity Score

1

**Comment by Pogman** [comment]
You could try opening he device and disconnecting the internal battery, wait a bit and reconnect.

CNL's are fairly robust and in all the years I've used (abused hah ha) them I've not had any issues. Usually CNL issues are down to worn ports and cables. The only time I use 'safely eject' is for memory sticks and drives so data gets written.

**Comment by bchris21** [comment]
Thanks a lot, I will give it a try today and report back!

**Comment by bchris21** [comment]
@Pogman your solution worked! Disconnecting the internal battery and leaving it disconnected for 1-2 minuted did the trick. Thanks a lot 👍
