### ISSUE TITLE
No protocol in Nightscout uploader

### ISSUE THREAD

**Issue by lulukuhl** [pazaan/600SeriesAndroidUploader#298]
#### Your Environment

* Uploader Version Number: v0.7.3
* Your Android Phone Model Name : Samsung S3 Galaxy
* Android Version Number (e.g. use 4.4 for 4.4.4): Android Version 4.3
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wifi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): no issue on Nightscout

#### Brief Explanation of Issue

I changed the uploader phone since the old one broke down, I stayed on a Samsung S3 since it has still a battery I can switch. The uploader version v0.7.3 works and also the upload to Nightscout works. BUT on the uploader app below the graph with the glucose there is NO protocol. Usually it tells me things like: next poll due in 30 seconds, or Nightscout available etc. But now it is just blank. What could be the issue? I tried deleting the protocol (although not existing), I tried re-starting the app. I don't know if there is some setting I need to change. 
Since the uploader phone is always with our kid in kindergarten, the protocol is really helpful when communicating with the teachers on possible errors. Thanks. 

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by Pogman** [comment]
There could be issues with really android versions and newer versions of the uploader. Try uninstalling version 0.7.3 and installing 0.7.1

https://github.com/pazaan/600SeriesAndroidUploader/releases/tag/v0.7.1

**Comment by lulukuhl** [comment]
Thank you. Indeed that seems to be the problem. I managed to get the protocol with the 0.7.1 version. As of 0.7.2 it doesn't work anymore. Good to know. I'll keep a copy of the 0.7.1 version just in case for future use. 
Thanks a lot for your support!
