### ISSUE TITLE
Upload existing Data to Nightscout

### ISSUE THREAD

**Issue by psit** [pazaan/600SeriesAndroidUploader#303]
#### Your Environment

* Uploader Version Number: 0.7.3
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung Galaxy S4
* Android Version Number (e.g. use 4.4 for 4.4.4): 5.0.1
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wifi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 14.2.2

#### Brief Explanation of Issue

I have 3 month of data in the uploader. I used it as a standalone "second screen" for the 640G. Now I got my Nightscout server up, but I only see old Treatments, no CGM values. New/current CGM values are beeing pushed to NS. Is there a way to push the old CGM data to NS as well?

#### Steps to Reproduce (for bugs)

1. Use uploader without NS configured for a while
2. Configure NS connection
3. Old CGM data is not uploaded, only current/recent one

#### Severity Score

1

**Comment by Pogman** [comment]
It should pull the cgm data and upload it with these settings. The default is 7 days, when set to 90 it will take a fair amount of time to complete.

![Screenshot 2021-03-09 143406](https://user-images.githubusercontent.com/7413594/110486425-8c51c500-80e4-11eb-964a-3af813864b62.jpg)

**Comment by psit** [comment]
The data has already been pulled from the pump (as I said, the uploader has been used for quite some time without NS as a "standalone second screen"), it's just not pushed to NS.

**Comment by Pogman** [comment]
You could try clearing the cache in your web browser for your NS site, sometimes helps if some data is not showing. Also try reinstalling the uploader as it will try to pull and upload again for the full period.

**Comment by psit** [comment]
It was not a caching problem in first place.
I grabbed another phone and installed the uploader there (I'm a bit paranoid. Never change a running system). Now all data is in NS!
The caching was still a problem watching the data dropping in on NS. Thanks for that hint.
