### ISSUE TITLE
FAQ - add one about phone charging with CNL attached

### ISSUE THREAD

**Issue by wright-david** [pazaan/600SeriesAndroidUploader#46]
...once we've figured it out ourselves

**Comment by niksimms** [comment]
Charging a OTG capable device while the external device is plugged in is problematic. Bypass Y cables require a certain resistor for each device.

**Comment by pheppy** [comment]
I've tried the "Micro USB Host OTG Cable with Micro USB Power". It works when using an USB flashdrive. But for the Bayer CNL it does not work. My Sony Xperia Z uses a charging cradle (with pogo pins) to charge. Some tweaking of the cradle will allow the USB OTG cable to be in when the phone is mounted (and charging). I should be able to get round the clock uploading working that way. If the uploader becomes better at re-establishing the connection with Bayer CNL when the Medtronics pump is returning from being out of range. In our case we put the phone and Bayer CNL in a small backpack our T1D takes with him anyway. There is no guarantee T1D will be within range of the Bayer CNL all the time. We stopped because every time it stoped working for the rest of the day after 20-30 minutes.

**Comment by volkerrichert** [comment]
I have a cable charging the phone while using CNL.

https://www.amazon.de/gp/product/B00M1H5348/ref=oh_aui_search_detailpage?ie=UTF8&psc=1

![](https://images-na.ssl-images-amazon.com/images/I/31RcbBtyYAL.jpg)

**Comment by wright-david** [comment]
There is now (2.5 years on!) a lot of information about this subject available in the Facebook support group posts, so I have attempted to collate the various tips in one place. 

Because github wiki pages are 'special' (do not support forking/branching etc.) I have made a demo page here: <https://github.com/wright-david/600-wiki-charging/wiki/FAQ-charging>

One thing I'm still unsure about is whether to put Wireless charging into the "Reliable solutions" section (where it currently is) or "Less realiable solutions".

Please let me know your feedback. @tlw46 in particular might recognise several quotes.

**Comment by tlw46** [comment]
This explanation in Github format is more extension (great information and explanation) than the FAQ #37 in our  Nightscout for Medtronic 600 Series FAQ  listed below.. The links below are contains links to Suppliers from other countries that have been reported to work on some devices (as stated they don’t work on all.) I have not found even one none Hub type that will work on any of my 8 uploader devices (Samsung Note 2, Galaxy 4, 5, 7, Note 8, Kindle Fire 8, 10, Moto E2). I also have a drawer full of Hubs, and Y splitters that will not work!

37: Where can we find a USB OTG adaptor module that will make it possible to both charge a Uploader device and connect to a CNL at the same time? Note - These are hit and miss in that they will works on some devices but not all!!!!

A: From AliExpress
https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20180711151005&SearchText=EastVita+4+Port+Micro+USB+OTG+Hub

Or From Amazon
https://www.amazon.com/gp/product/B00U90AM04/ref=ppx_yo_dt_b_asin_title_o01__o00_s00?ie=UTF8&psc=1<https://www.amazon.com/gp/product/B00U90AM04/ref=ppx_yo_dt_b_asin_title_o01__o00_s00?ie=UTF8&psc=1Or>

Or From eBay
 https://www.ebay.com/ Search For: ELEGIANT 4 Port Micro USB-Power Charging OTG Hub Cable For Android Tablet Phone

Or From eBay - United Kingdom
https://www.ebay.co.uk/itm/231798195824?ul_noapp=true

Or From eBay - Austrialia https://www.ebay.com.au/itm/4-Port-Micro-USB-2-0-OTG-Charger-HUB-Data-Cable-For-Tablet-Smart-Phone-AQ/323001108191

**Comment by Pogman** [comment]
Looks good.

An easy to update list of specific phones + what works on them would be useful.

**Comment by wright-david** [comment]
Many thanks for the comments.

After checking with tlw I decided to leave the list of possible USB OTG hubs to the Facebook group docs. 
Although a list of what works on which phone is a good idea, again it would probably be easier to update in a doc on the Fb group.

Just pushed to
https://github.com/pazaan/600SeriesAndroidUploader/wiki/FAQ-charging

If you are ok with this please close this issue (as although I tried 'closes' in the commit comment, it didn't work with the wiki).

**Comment by Pogman** [comment]
👍 cool... will attempt to close for you
