### ISSUE TITLE
Mismatch of IOB after 2 boluses

### ISSUE THREAD

**Issue by pazaan** [pazaan/600SeriesAndroidUploader#55]
Hi
I realised, that the IOB was mismatched after I've applied one bolus of 7.4 U at 1:05pm and 6.0 U at 1:17 pm. The IOB then first showed the insulin of the first bolus until it was down to 0 again, then suddenly the IOB of the second bolus appeared also. The pump showed the whole bolus amount on board, as usual.

Seems like it can't add them together? 
I've updated to the dev branch. I don't understand much of that, could also be possible, that I've done something wrong there. Btw I also don't get any rawbg data, although activated in ENABLE variables. 
Insulin duration is set to 3hrs in all devices.

My Gear

Minimed 640G, Enlite Sensor
Samsung Galaxy S4 Android 5.0.1, Carelink next link 2.4
Uploader version 0.2.1
Greetings
Dominik

**Comment by Pogman** [comment]
Hi - I'm a little confused be IOB and NS. I thought that the uploader would transfer IOB from the pump data and show that on a NS site but it seems to be that this is not the way it works. 

This is pulled from NS info: "IOB in Nightscout depends on accurate, manual Care Portal data entry and is not derived from any pump data."

**Comment by dompy** [comment]
Well you have to update/merge to/the dev branch for getting IOB directly from the 640G pump

**Comment by volkerrichert** [comment]
still an issue?

**Comment by pazaan** [comment]
Let me check that I've fixed this in the code - it's because IOB is actually a 2-byte value, and I was only using the lowest byte to read the data...

**Comment by pazaan** [comment]
It's fixed in my dev branch. This issue should auto-close once it's merged into master.
