### ISSUE TITLE
Translation into Spanish

### ISSUE THREAD

**Issue by marcosdetry** [pazaan/600SeriesAndroidUploader#66]
I am willing to contribute with Spanish translation.
When you have the strings that can be localized, just let me know and I will translate them.
thanks for your effort in this project. marcos

I see most of strings are in Values/Strings. Please let me know if this is ready to be localized.

**Comment by volkerrichert** [comment]
hi marcosdetry,

feel free to set up localized strings and start with the spanish translation. PR are welcome.

**Comment by pazaan** [comment]
Closed in favour of https://github.com/pazaan/600SeriesAndroidUploader/issues/220
