### ISSUE TITLE
Failure to support change over to new 640g/CNL combo

### ISSUE THREAD

**Issue by wright-david** [pazaan/600SeriesAndroidUploader#71]
Uploader Version Number: 0.3.1
#### Brief Explanation of Issue

A number of users have reported problems with previously working Nightscout sites (both before and after NS 0.9.0), when they have started using a new 640g (e.g. after pump failure) despite uploading to Carelink website via the upload CNL.
The problem has been resolved by reinstalling the app, or (in at least one case) clearing the App's data and cache, and then re-registering the CNL.

_I suspect (but have not tested) that the same might apply to using the original 640g and a new CNL_
#### Severity Score

2 - takes users offline until resolved (in one case someone was abroad on holiday at the time)

**Comment by pazaan** [comment]
This requires users to uninstall/reinstall the app, as well as re-pairing the CNL and pump

**Comment by volkerrichert** [comment]
Changing the pump with known CNL is still an issue. I found no stable way to test this. GetPumptime will just fail. That's just an indirect indicator.

**Comment by pazaan** [comment]
Fixed by #143
