### ISSUE TITLE
Re-badging the uploader

### ISSUE THREAD

**Issue by wright-david** [pazaan/600SeriesAndroidUploader#73]
As the 640g uploader can be used for 630g and 670g too, it should be renamed to avoid confusing new users.

Note - distinction needs to be retained with respect to the Veo/530g uploader
_(so one suggestion to call it the 'gUploader' is flawed)_

Of course this entails tons of effort ...

**Comment by Pogman** [comment]
![6-up](https://cloud.githubusercontent.com/assets/7413594/19583951/9dca513e-9738-11e6-93b0-39e6d5b63f64.png)
