### ISSUE TITLE
receive "missed" SG values 

### ISSUE THREAD

**Issue by volkerrichert** [pazaan/600SeriesAndroidUploader#74]
If the pump is moved away from CNL the uploader will miss SG values (and other) for a period of time (maybe hours). It would be create it they will be collected from pump after reconnecting. To keep ist simpler only the values between last received value and now. The values should be store in pump AFAIK.
- Uploader Version Number: 0.4.0-Snapshot
- Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung S4
- Android Version Number (e.g. use 4.4 for 4.4.4): 5.0

Volker

**Comment by Pogman** [comment]
done ;)
