### ISSUE TITLE
api call of devicestatus doesn't seem to support bulk upload

### ISSUE THREAD

**Issue by volkerrichert** [pazaan/600SeriesAndroidUploader#80]
I have the effect that the devicestatus will not be updated. After some digging into both sources i found the Uploader send an array of status e.g.

[{"uploaderBattery":96,"device":"medtronic-640g:\/\/6212-1051393","pump":{"clock":"2016-11-06T11:48:30+0100","reservoir":24.575000762939453,"iob":{"timestamp":"Sun Nov 06 11:48:30 MEZ 2016","bolusiob":0.5},"battery":{"percent":50}}}]

but the API seem just want to have support for single data

inside /lib/devicestatus.js you will find

  function create(obj, fn) {
    if (! obj.hasOwnProperty('created_at')){
      obj.created_at = (new Date()).toISOString();
    }  
  ...

but in /lib/entries.js

// store new documents using the storage mechanism
  function create (docs, fn) {
    with_collection(function(err, collection) {
  ...

witch seem to me a bulk upload support.

I think submitting only the last value can be a solution or eveny one in a single post. I'll open in issue at nightscout

**Comment by volkerrichert** [comment]
one more point: the uploader had(!) submitted device status somehow. But WTF, i don't understand why this happend...

**Comment by pazaan** [comment]
I have added bulk-uploading in my local code, which I'm currently testing.

**Comment by volkerrichert** [comment]
Do you mean your NS source?

We should add some kind of NS-Detection using /api/v1/status.json and change our behavior. Something like NightscoutGrilledCheeseUploadIntentService or package info.nightscout.android.upload.nightscout.grilledcheese and a factory to handle version changes.

**Comment by volkerrichert** [comment]
or info.nightscout.android.upload.nightscout.grilledcheese092

**Comment by volkerrichert** [comment]
there are single uploads implemented. but we should keep this as a reminder if NS changes the API

**Comment by Pogman** [comment]
closing as very out of date... wow time flies, 2016 blimey.
