### ISSUE TITLE
Error connecting to Contour Next Link

### ISSUE THREAD

**Issue by vitalev** [pazaan/600SeriesAndroidUploader#94]
#### Your Environment

* Uploader Version Number: 0.4.0-SNAPSHOT
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Huawei P8 
* Android Version Number (e.g. use 4.4 for 4.4.4): 6.0
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): WiFi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 0.9.2 head

#### Uploader Error Code

Connecting to Countour Next Link..
Conneected to Contour Next Link on channel 17
Error connecting to Contour Next Link
Connecting to Countour Next Link..
Error connecting to Contour Next Link

#### Steps to Reproduce (for bugs)

1.Unplug usb otg cable, plug usb otg cable
2.App start and excluded from the Power Saving Setting
3.Connecting to Countour Next Link..
Conneected to Contour Next Link on channel 17
4.Ramdomly display view 
Connecting to Countour Next Link..
Conneected to Contour Next Link on channel 17
5. Pump Status not diplayed
    Uploader Status not diplayed
    CGM Starus not diplayed
    Nightscout Status not diplayed
#### Severity Score

4

**Comment by volkerrichert** [comment]
the status page is just a dummy at the moment.

is there a message on the CNL?

**Comment by vitalev** [comment]
Hello,
I do not receive any messages, but I occasionally hear a beep, like I had
reconnected CNL to the phone.

Il 05/gen/2017 21:09, "volkerrichert" <notifications@github.com> ha scritto:

the status page is just a dummy at the moment.

is there a message on the CNL?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pazaan/640gAndroidUploader/issues/94#issuecomment-270744128>,
or mute the thread

**Comment by volkerrichert** [comment]
is there also a disconnect notification?

**Comment by vitalev** [comment]
Aren't disconnect comunication.
How can I make an application debugging?

**Comment by volkerrichert** [comment]
You can debug it as usual... Using the normal IDE. Remote debugging is recommended, because you need CNL to be plugged in.... Sometimes i'll do debuggng using genymotion. It's Virtualbox based and you can map the CNL into the VM

**Comment by volkerrichert** [comment]
is it still an issue?

**Comment by pazaan** [comment]
Fixed by #143

**Comment by edepalos** [comment]
So how it was fixed?
